# Data Wrangling Individual Player Stats

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

from urllib.request import urlopen
from bs4 import BeautifulSoup

pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)

In [2]:
# define function that will scrap information from basketball-reference.com and return information as a dataframe

def basketball_reference_scrap(year, statistic):
    # URL page we will be scraping 
    url = 'https://www.basketball-reference.com/leagues/NBA_{}_{}.html'.format(year, statistic)
    html = urlopen(url)
    soup = BeautifulSoup(html)
    headers = [th.getText() for th in soup.findAll('tr', limit=2)[0].findAll('th')]
    # exclude the first column as we will not need the ranking order
    headers = headers[1:]
    rows = soup.findAll('tr')[1:]
    player_stats = [[td.getText() for td in rows[i].findAll('td')] for i in range(len(rows))]
    # create new dataframe
    df = pd.DataFrame(player_stats, columns = headers)
    df['Year'] = year
    return df

In [3]:
# create dataframe for 2018 per possession stats
per_poss2018 = basketball_reference_scrap(2018, 'per_poss')

per_poss2018.head(5)

          Player Pos Age   Tm   G  GS    MP   FG   FGA   FG%   3P   3PA   3P%   2P   2PA   2P%   FT  FTA   FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg DRtg  Year
0   Alex Abrines  SG  24  OKC  75   8  1134  5.0  12.7  .395  3.7   9.7  .380  1.4   3.1  .443  1.7  2.0  .848  1.1  3.9   5.0  1.2  1.7  0.4  1.1  5.4  15.4    116  110  2018
1     Quincy Acy  PF  27  BRK  70   8  1359  4.6  13.0  .356  3.6  10.4  .349  1.0   2.6  .384  1.8  2.1  .817  1.4  7.8   9.2  2.0  1.2  1.0  2.1  5.3  14.7     99  110  2018
2   Steven Adams   C  24  OKC  76  76  2487  8.9  14.2  .629  0.0   0.0  .000  8.9  14.2  .631  3.2  5.7  .559  7.7  6.0  13.7  1.8  1.8  1.6  2.6  4.3  21.1    125  107  2018
3    Bam Adebayo   C  20  MIA  69  19  1368  6.4  12.5  .512  0.0   0.3  .000  6.4  12.2  .523  4.7  6.6  .721  4.3  9.7  14.0  3.7  1.2  1.5  2.4  5.1  17.5    116  105  2018
4  Arron Afflalo  SG  32  ORL  53   3   682  4.7  11.6  .401  1.9   5.0  .386  2.7   6.6  .413  1.6  1.9  .846  0.3  4.5   4.7  2.2  0.3  0.6  1.5  4.0  12.8     98  115  2018

In [4]:
# check out shape of 2018 per possession dataframe
print(per_poss2018.shape)

(690, 32)

In [5]:
# check for duplicate entries
per_poss2018.duplicated().sum()

25

In [6]:
per_poss2018[per_poss2018.duplicated(subset='Player')].head(10)

             Player   Pos   Age    Tm     G    GS    MP    FG   FGA   FG%    3P   3PA   3P%    2P   2PA   2P%    FT   FTA   FT%   ORB   DRB   TRB   AST   STL   BLK   TOV    PF   PTS        ORtg  DRtg  Year
24        Omer Asik     C    31   NOP    14     0   121   2.8   6.3  .438   0.0   0.0         2.8   6.3  .438   1.6   4.7  .333   2.8  11.8  14.6   0.8   0.4   0.8   2.0   5.5   7.1          85   109  2018
25        Omer Asik     C    31   CHI     4     0    61   1.6   4.8  .333   0.0   0.0         1.6   4.8  .333   0.0   0.8  .000   1.6   6.4   8.0   0.8   0.8   1.6   3.2   4.8   3.2          52   112  2018
28     Luke Babbitt    SF    28   ATL    37     9   570   6.9  14.4  .476   4.2   9.5  .441   2.7   4.9  .544   1.5   1.9  .773   0.4   6.5   6.9   2.2   0.6   0.4   1.3   4.0  19.4         119   114  2018
29     Luke Babbitt    SF    28   MIA    13     5   145   3.8  16.3  .234   3.8  15.6  .244   0.0   0.7  .000   0.0   0.0         0.7   4.5   5.2   1.7   0.3   0.7   1.4   2.4  11.4          74   111  2018
45  Marco Belinelli    SG    31   ATL    52     1  1210   8.0  19.6  .410   3.7  10.0  .372   4.3   9.6  .450   4.1   4.4  .927   0.6   3.5   4.0   4.2   1.9   0.1   2.2   1.7  23.9         109   113  2018
46  Marco Belinelli    SG    31   PHI    28     1   737   9.0  18.2  .495   3.7   9.7  .385   5.3   8.5  .618   3.1   3.5  .870   0.4   2.9   3.3   2.9   1.3   0.6   2.6   3.3  24.8         114   109  2018
47             None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  2018
60     Eric Bledsoe    PG    28   PHO     3     3    83   9.2  23.1  .400   2.3   7.5  .308   6.9  15.6  .444   6.3   8.1  .786   1.7   2.3   4.0   5.2   2.3   1.2   5.8   3.5  27.1          94   113  2018
61     Eric Bledsoe    PG    28   MIL    71    71  2239  10.1  21.1  .476   2.7   7.7  .349   7.4  13.4  .550   5.4   6.7  .795   1.1   5.1   6.2   8.0   3.2   0.9   4.6   4.0  28.2         109   108  2018
69    Trevor Booker    PF    30   BRK    18     6   395   9.5  18.4  .513   0.4   1.5  .250   9.1  17.0  .536   2.9   5.3  .558   4.7  10.0  14.6   4.7   1.0   0.6   3.7   5.3  22.2         105   110  2018

As we can see above, it looks like most of the duplicated entries are due to players having played on more than one team during the season. Let's fix this by creating a function that [drops](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) the duplicated players, given a dataframe as input.

In [7]:
def drop_duplicate_players(df):
    df.drop_duplicates(subset = 'Player', inplace=True)
    return df

In [8]:
drop_duplicate_players(per_poss2018);

In [9]:
per_poss2018.iloc[20:33, :]

             Player   Pos   Age    Tm     G    GS    MP    FG   FGA   FG%    3P   3PA   3P%    2P   2PA   2P%    FT   FTA   FT%   ORB   DRB   TRB   AST   STL   BLK   TOV    PF   PTS        ORtg  DRtg  Year
20             None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  2018
21   Darrell Arthur    PF    29   DEN    19     1   141   7.7  16.5  .468   2.8   8.1  .348   4.9   8.4  .583   0.7   1.1  .667   1.1   4.2   5.3   3.2   2.8   1.1   5.3   7.7  19.0          90   109  2018
22      Jamel Artis    SG    25   ORL    15     1   279   5.4  13.9  .392   1.4   5.1  .276   4.0   8.8  .460   1.2   2.1  .583   0.7   6.0   6.7   3.2   0.4   0.5   1.4   1.9  13.5          94   114  2018
23        Omer Asik     C    31   TOT    18     0   182   2.4   5.8  .409   0.0   0.0         2.4   5.8  .409   1.1   3.4  .308   2.4  10.0  12.4   0.8   0.5   1.1   2.4   5.3   5.8          76   110  2018
26    D.J. Augustin    PG    30   ORL    75    36  1760   6.8  15.0  .452   3.2   7.6  .419   3.6   7.5  .485   4.6   5.3  .868   0.8   3.6   4.5   8.0   1.5   0.0   3.4   2.6  21.3         116   114  2018
27     Luke Babbitt    SF    28   TOT    50    14   715   6.3  14.8  .423   4.1  10.7  .385   2.1   4.1  .525   1.2   1.5  .773   0.5   6.1   6.6   2.1   0.5   0.5   1.3   3.7  17.8         109   113  2018
30     Dwayne Bacon    SG    22   CHO    53     6   713   4.9  13.1  .375   0.8   2.9  .256   4.2  10.2  .409   1.4   1.7  .800   0.3   8.2   8.5   2.6   1.1   0.1   1.6   3.1  12.0          88   111  2018
31        Ron Baker    SG    24   NYK    29     1   385   2.6   7.6  .339   1.4   4.2  .333   1.2   3.3  .346   2.6   3.3  .769   0.6   3.2   3.9   6.1   3.3   0.8   2.3   4.2   9.1         104   109  2018
32     Wade Baldwin    PG    21   POR     7     0    80   8.7  13.1  .667   2.5   3.1  .800   6.2  10.0  .625   3.7   6.2  .600   0.6   4.4   5.0   3.1   1.2   0.6   2.5   7.5  23.6         131   109  2018
33       Lonzo Ball    PG    20   LAL    52    50  1780   5.5  15.2  .360   2.4   7.9  .305   3.0   7.2  .420   0.9   1.9  .451   1.9   7.8   9.7  10.1   2.4   1.2   3.7   3.1  14.2          97   106  2018
34       J.J. Barea    PG    33   DAL    69    10  1603   9.5  21.6  .439   3.6   9.8  .367   5.9  11.8  .499   2.5   3.2  .784   0.5   5.8   6.3  13.6   1.1   0.1   4.5   2.6  25.1         109   112  2018
35  Harrison Barnes    PF    25   DAL    77    77  2634  10.2  23.0  .445   2.3   6.3  .357   8.0  16.7  .478   4.9   6.0  .827   1.5   7.5   8.9   2.9   0.9   0.3   2.2   1.8  27.7         105   111  2018
36      Will Barton    SG    27   DEN    81    40  2683   8.6  19.0  .452   2.9   7.8  .370   5.7  11.2  .510   3.4   4.2  .805   1.3   6.3   7.6   6.1   1.5   1.0   2.8   3.1  23.4         113   112  2018

As we can see above, the function `drop_duplicate_players` did indeed drop the extra entries. In this specific example, we can see that the extra entries of `Omer Asik` and `Luke Babbitt` were removed. _But_ we still have to address the `None` entries.

- [pandas.DataFrame.fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) documentation

In [10]:
per_poss2018.isnull().sum()

Player    1
Pos       1
Age       1
Tm        1
G         1
GS        1
MP        1
FG        1
FGA       1
FG%       1
3P        1
3PA       1
3P%       1
2P        1
2PA       1
2P%       1
FT        1
FTA       1
FT%       1
ORB       1
DRB       1
TRB       1
AST       1
STL       1
BLK       1
TOV       1
PF        1
PTS       1
          1
ORtg      1
DRtg      1
Year      0
dtype: int64

It looks like the additional `None` rows were eliminated when we executed the `drop_duplicate_players` function, which makes sense seeing as they appeared in tandem with the duplicated players from earlier.

Another interesting observation: there appears to be a blank column as well. We'll address this in a little bit but first, let's take care of the `None` in row 20.

In [11]:
# replace 'None' rows with 'NaN'
per_poss2018.fillna(value=pd.np.nan, inplace = True)

In [12]:
# replace 'None' rows with 'NaN'
per_poss2018.iloc[16:22, :]

              Player  Pos  Age   Tm    G   GS    MP   FG   FGA   FG%   3P   3PA   3P%   2P   2PA   2P%   FT  FTA   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS      ORtg DRtg  Year
16   Carmelo Anthony   PF   33  OKC   78   78  2501  9.4  23.2  .404  3.4   9.4  .357  6.0  13.8  .437  2.9  3.8  .767  1.3  7.7  9.0  2.0  0.9  1.0  2.0  3.9  25.0       104  109  2018
17        OG Anunoby   SF   20  TOR   74   62  1481  5.4  11.5  .471  2.4   6.6  .371  3.0   5.0  .604  1.3  2.1  .629  1.5  4.7  6.1  1.8  1.7  0.5  1.5  4.3  14.6       113  108  2018
18  Ryan Arcidiacono   PG   23  CHI   24    0   304  2.7   6.6  .415  1.4   5.0  .290  1.3   1.6  .800  0.8  1.0  .833  0.2  3.9  4.0  5.6  2.1  0.0  2.1  2.9   7.7       105  112  2018
19      Trevor Ariza   SF   32  HOU   67   67  2269  5.8  14.1  .412  3.7  10.0  .368  2.1   4.1  .519  1.6  1.9  .854  0.7  5.7  6.4  2.3  2.1  0.3  1.1  2.9  17.0       114  107  2018
20               NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN  NaN  2018
21    Darrell Arthur   PF   29  DEN   19    1   141  7.7  16.5  .468  2.8   8.1  .348  4.9   8.4  .583  0.7  1.1  .667  1.1  4.2  5.3  3.2  2.8  1.1  5.3  7.7  19.0        90  109  2018

In [13]:
# pre-drop shape
per_poss2018.shape

(541, 32)

In [14]:
# dropna rows inplace
per_poss2018.dropna(axis = 0, inplace = True)

In [15]:
# post dropna shape
per_poss2018.shape

(540, 32)

Cool! Looks like we dropped the (lone) row with NaN's! Now we need to address the 'blank' column.

In [16]:
per_poss2018[''].head(5)

0
1
2
3
4
Name: , dtype: object

As we can see, there is no input for this column so we'll just drop it, similar to what we did with the `NaN` row.

In [17]:
per_poss2018.drop(labels = '', axis = 1, inplace = True)

In [18]:
per_poss2018.head(5)

          Player Pos Age   Tm   G  GS    MP   FG   FGA   FG%   3P   3PA   3P%   2P   2PA   2P%   FT  FTA   FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS ORtg DRtg  Year
0   Alex Abrines  SG  24  OKC  75   8  1134  5.0  12.7  .395  3.7   9.7  .380  1.4   3.1  .443  1.7  2.0  .848  1.1  3.9   5.0  1.2  1.7  0.4  1.1  5.4  15.4  116  110  2018
1     Quincy Acy  PF  27  BRK  70   8  1359  4.6  13.0  .356  3.6  10.4  .349  1.0   2.6  .384  1.8  2.1  .817  1.4  7.8   9.2  2.0  1.2  1.0  2.1  5.3  14.7   99  110  2018
2   Steven Adams   C  24  OKC  76  76  2487  8.9  14.2  .629  0.0   0.0  .000  8.9  14.2  .631  3.2  5.7  .559  7.7  6.0  13.7  1.8  1.8  1.6  2.6  4.3  21.1  125  107  2018
3    Bam Adebayo   C  20  MIA  69  19  1368  6.4  12.5  .512  0.0   0.3  .000  6.4  12.2  .523  4.7  6.6  .721  4.3  9.7  14.0  3.7  1.2  1.5  2.4  5.1  17.5  116  105  2018
4  Arron Afflalo  SG  32  ORL  53   3   682  4.7  11.6  .401  1.9   5.0  .386  2.7   6.6  .413  1.6  1.9  .846  0.3  4.5   4.7  2.2  0.3  0.6  1.5  4.0  12.8   98  115  2018

Things are starting to look really good! Let's use `info()` to get a high-level perspective of the dataframe.

In [19]:
per_poss2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 689
Data columns (total 31 columns):
Player    540 non-null object
Pos       540 non-null object
Age       540 non-null object
Tm        540 non-null object
G         540 non-null object
GS        540 non-null object
MP        540 non-null object
FG        540 non-null object
FGA       540 non-null object
FG%       540 non-null object
3P        540 non-null object
3PA       540 non-null object
3P%       540 non-null object
2P        540 non-null object
2PA       540 non-null object
2P%       540 non-null object
FT        540 non-null object
FTA       540 non-null object
FT%       540 non-null object
ORB       540 non-null object
DRB       540 non-null object
TRB       540 non-null object
AST       540 non-null object
STL       540 non-null object
BLK       540 non-null object
TOV       540 non-null object
PF        540 non-null object
PTS       540 non-null object
ORtg      540 non-null object
DRtg      540 non-null object
Year      540 non-null int64
dtypes: int64(1), object(30)
memory usage: 135.0+ KB

Looks like we were a little early with the celebration. No worries, just have to change all the columns except `Player`, `Pos`, `Age`, `Tm`, and `Year` to numerics.

In [20]:
# convert statistical columns to numerics; first get list of columns to convert
cols_to_numeric = per_poss2018.columns.drop(['Player', 'Pos', 'Age', 'Tm', 'Year'])

In [21]:
# convert selected columns to numeric dtypes
per_poss2018[cols_to_numeric].apply(pd.to_numeric, errors = 'coerce').head(10)

    G  GS    MP    FG   FGA    FG%   3P   3PA    3P%    2P   2PA    2P%   FT  FTA    FT%  ORB   DRB   TRB  AST  STL  BLK  TOV    PF   PTS   ORtg  DRtg
0  75   8  1134   5.0  12.7  0.395  3.7   9.7  0.380   1.4   3.1  0.443  1.7  2.0  0.848  1.1   3.9   5.0  1.2  1.7  0.4  1.1   5.4  15.4  116.0   110
1  70   8  1359   4.6  13.0  0.356  3.6  10.4  0.349   1.0   2.6  0.384  1.8  2.1  0.817  1.4   7.8   9.2  2.0  1.2  1.0  2.1   5.3  14.7   99.0   110
2  76  76  2487   8.9  14.2  0.629  0.0   0.0  0.000   8.9  14.2  0.631  3.2  5.7  0.559  7.7   6.0  13.7  1.8  1.8  1.6  2.6   4.3  21.1  125.0   107
3  69  19  1368   6.4  12.5  0.512  0.0   0.3  0.000   6.4  12.2  0.523  4.7  6.6  0.721  4.3   9.7  14.0  3.7  1.2  1.5  2.4   5.1  17.5  116.0   105
4  53   3   682   4.7  11.6  0.401  1.9   5.0  0.386   2.7   6.6  0.413  1.6  1.9  0.846  0.3   4.5   4.7  2.2  0.3  0.6  1.5   4.0  12.8   98.0   115
5  21   0    49   5.1  15.3  0.333  0.0   0.0    NaN   5.1  15.3  0.333  2.0  6.1  0.333  3.1  12.2  15.3  3.1  2.0  1.0  1.0  11.2  12.2   85.0   107
6  75  75  2509  13.8  27.1  0.510  0.5   1.9  0.293  13.3  25.3  0.526  6.7  8.0  0.837  5.0   7.8  12.8  3.1  0.9  1.8  2.2   3.2  34.9  118.0   105
7  72  31  1441   7.9  13.4  0.589  0.2   0.5  0.333   7.7  12.9  0.599  3.8  5.0  0.776  4.9   8.2  13.1  1.7  0.9  3.0  2.8   5.0  19.8  119.0   108
8  18   1   107   2.8  10.3  0.273  0.0   5.1  0.000   2.8   5.1  0.545  3.3  4.2  0.778  1.9   3.3   5.1  5.6  1.4  0.9  4.2   7.0   8.9   78.0   106
9  22   0   273   7.7  15.9  0.484  0.7   2.1  0.333   7.0  13.8  0.506  1.9  3.7  0.524  3.5   4.7   8.2  1.6  1.9  0.5  3.3   8.6  18.0   95.0   110

In [22]:
per_poss2018[cols_to_numeric] = per_poss2018[cols_to_numeric].apply(pd.to_numeric, errors = 'coerce')

In [23]:
# recheck info of per_poss2018
per_poss2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 689
Data columns (total 31 columns):
Player    540 non-null object
Pos       540 non-null object
Age       540 non-null object
Tm        540 non-null object
G         540 non-null int64
GS        540 non-null int64
MP        540 non-null int64
FG        540 non-null float64
FGA       540 non-null float64
FG%       537 non-null float64
3P        540 non-null float64
3PA       540 non-null float64
3P%       491 non-null float64
2P        540 non-null float64
2PA       540 non-null float64
2P%       527 non-null float64
FT        540 non-null float64
FTA       540 non-null float64
FT%       501 non-null float64
ORB       540 non-null float64
DRB       540 non-null float64
TRB       540 non-null float64
AST       540 non-null float64
STL       540 non-null float64
BLK       540 non-null float64
TOV       540 non-null float64
PF        540 non-null float64
PTS       540 non-null float64
ORtg      538 non-null float64
DRtg      540 non-null int64
Year      540 non-null int64
dtypes: float64(22), int64(5), object(4)
memory usage: 135.0+ KB

In [24]:
# one last peek at the final product
per_poss2018.head(5)

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg  DRtg  Year
0   Alex Abrines  SG  24  OKC  75   8  1134  5.0  12.7  0.395  3.7   9.7  0.380  1.4   3.1  0.443  1.7  2.0  0.848  1.1  3.9   5.0  1.2  1.7  0.4  1.1  5.4  15.4  116.0   110  2018
1     Quincy Acy  PF  27  BRK  70   8  1359  4.6  13.0  0.356  3.6  10.4  0.349  1.0   2.6  0.384  1.8  2.1  0.817  1.4  7.8   9.2  2.0  1.2  1.0  2.1  5.3  14.7   99.0   110  2018
2   Steven Adams   C  24  OKC  76  76  2487  8.9  14.2  0.629  0.0   0.0  0.000  8.9  14.2  0.631  3.2  5.7  0.559  7.7  6.0  13.7  1.8  1.8  1.6  2.6  4.3  21.1  125.0   107  2018
3    Bam Adebayo   C  20  MIA  69  19  1368  6.4  12.5  0.512  0.0   0.3  0.000  6.4  12.2  0.523  4.7  6.6  0.721  4.3  9.7  14.0  3.7  1.2  1.5  2.4  5.1  17.5  116.0   105  2018
4  Arron Afflalo  SG  32  ORL  53   3   682  4.7  11.6  0.401  1.9   5.0  0.386  2.7   6.6  0.413  1.6  1.9  0.846  0.3  4.5   4.7  2.2  0.3  0.6  1.5  4.0  12.8   98.0   115  2018

In [25]:
per_poss2018.tail(5)

           Player Pos Age   Tm   G  GS    MP    FG   FGA    FG%   3P  3PA    3P%    2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg  DRtg  Year
683   Cody Zeller   C  25  CHO  33   0   627   6.6  12.1  0.545  0.2  0.2  0.667   6.5  11.9  0.542  4.7  6.6  0.718  5.2  8.6  13.8  2.4  1.1  1.6  2.6  6.3  18.1  119.0   108  2018
684  Tyler Zeller   C  28  TOT  66  34  1109   8.3  14.8  0.560  0.4  1.2  0.357   7.8  13.5  0.578  2.5  3.5  0.722  4.9  8.6  13.5  2.1  0.7  1.5  2.1  5.6  19.5  118.0   111  2018
687   Paul Zipser  SF  23  CHI  54  12   824   4.8  13.9  0.346  2.2  6.5  0.336   2.6   7.3  0.355  1.1  1.5  0.760  0.8  7.0   7.8  2.7  1.2  0.9  2.5  5.1  12.9   84.0   112  2018
688    Ante Zizic   C  21  CLE  32   2   214  11.2  15.3  0.731  0.0  0.0    NaN  11.2  15.3  0.731  4.8  6.6  0.724  5.5  8.2  13.7  1.1  0.5  3.0  2.5  6.9  27.2  137.0   111  2018
689   Ivica Zubac   C  20  LAL  43   0   410   7.1  14.2  0.500  0.0  0.1  0.000   7.1  14.1  0.504  4.6  6.0  0.765  5.3  9.1  14.4  2.9  0.9  1.8  3.0  5.5  18.8  111.0   107  2018

Alright, looks like this dataset is almost good to go! One last housekeeping task: reset the index. Remember how we dropped rows? Well now there are gaps in the indexes for the rows. This is a simple and quick fix using `reset_index`.

- [How To Reset Index in Pandas DataFrame](https://cmdlinetips.com/2018/04/how-to-reset-index-in-pandas-dataframe/)

In [26]:
per_poss2018.reset_index(drop=True, inplace = True);

In [27]:
per_poss2018.tail()

           Player Pos Age   Tm   G  GS    MP    FG   FGA    FG%   3P  3PA    3P%    2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg  DRtg  Year
535   Cody Zeller   C  25  CHO  33   0   627   6.6  12.1  0.545  0.2  0.2  0.667   6.5  11.9  0.542  4.7  6.6  0.718  5.2  8.6  13.8  2.4  1.1  1.6  2.6  6.3  18.1  119.0   108  2018
536  Tyler Zeller   C  28  TOT  66  34  1109   8.3  14.8  0.560  0.4  1.2  0.357   7.8  13.5  0.578  2.5  3.5  0.722  4.9  8.6  13.5  2.1  0.7  1.5  2.1  5.6  19.5  118.0   111  2018
537   Paul Zipser  SF  23  CHI  54  12   824   4.8  13.9  0.346  2.2  6.5  0.336   2.6   7.3  0.355  1.1  1.5  0.760  0.8  7.0   7.8  2.7  1.2  0.9  2.5  5.1  12.9   84.0   112  2018
538    Ante Zizic   C  21  CLE  32   2   214  11.2  15.3  0.731  0.0  0.0    NaN  11.2  15.3  0.731  4.8  6.6  0.724  5.5  8.2  13.7  1.1  0.5  3.0  2.5  6.9  27.2  137.0   111  2018
539   Ivica Zubac   C  20  LAL  43   0   410   7.1  14.2  0.500  0.0  0.1  0.000   7.1  14.1  0.504  4.6  6.0  0.765  5.3  9.1  14.4  2.9  0.9  1.8  3.0  5.5  18.8  111.0   107  2018

Now it's time to export the data!

In [28]:
per_poss2018.to_csv('data/df_perposs2018')

## Scrap Advanced Stats and Combine With Per Possession DataFrame

In [29]:
# create dataframe for 2018 advanced stats
advanced2018 = basketball_reference_scrap(2018, 'advanced')

In [30]:
advanced2018.head(10)

              Player Pos Age   Tm   G    MP   PER   TS%  3PAr   FTr  ORB%  DRB%  TRB%  AST% STL% BLK%  TOV%  USG%     OWS  DWS    WS   WS/48    OBPM  DBPM   BPM  VORP  Year
0       Alex Abrines  SG  24  OKC  75  1134   9.0  .567  .759  .158   2.5   8.9   5.6   3.4  1.7  0.6   7.4  12.7     1.3  1.0   2.2    .094    -0.5  -1.7  -2.2  -0.1  2018
1         Quincy Acy  PF  27  BRK  70  1359   8.2  .525  .800  .164   3.1  17.1  10.0   6.0  1.2  1.6  13.3  14.4    -0.1  1.1   1.0    .036    -2.0  -0.2  -2.2  -0.1  2018
2       Steven Adams   C  24  OKC  76  2487  20.6  .630  .003  .402  16.6  13.9  15.3   5.5  1.8  2.8  13.3  16.7     6.7  3.0   9.7    .187     2.2   1.1   3.3   3.3  2018
3        Bam Adebayo   C  20  MIA  69  1368  15.7  .570  .021  .526   9.7  21.6  15.6  11.0  1.2  2.5  13.6  15.9     2.3  1.9   4.2    .148    -1.6   1.8   0.2   0.8  2018
4      Arron Afflalo  SG  32  ORL  53   682   5.8  .516  .432  .160   0.6  10.1   5.3   6.2  0.3  1.1  10.8  12.5    -0.1  0.2   0.1    .009    -4.1  -1.8  -5.8  -0.7  2018
5       Cole Aldrich   C  29  MIN  21    49   6.0  .340  .000  .400   7.0  28.6  17.6   8.2  2.0  1.8   5.4  16.8    -0.1  0.1   0.0  -0.013    -7.0   0.1  -6.9  -0.1  2018
6  LaMarcus Aldridge   C  32  SAS  75  2509  25.0  .570  .068  .296  10.8  17.3  14.0  11.3  0.9  3.0   6.8  29.1     7.4  3.5  10.9    .209     3.0   0.3   3.3   3.3  2018
7      Jarrett Allen   C  19  BRK  72  1441  17.5  .636  .038  .370  10.5  18.1  14.3   5.4  0.9  4.6  15.1  16.3     2.7  1.5   4.2    .141    -1.3   1.4   0.2   0.8  2018
8       Kadeem Allen  PG  25  BOS  18   107   2.6  .366  .500  .409   4.1   7.1   5.6  15.2  1.4  1.6  25.7  14.6    -0.2  0.1  -0.1  -0.038    -6.7   0.3  -6.4  -0.1  2018
9         Tony Allen  SF  36  NOP  22   273   8.7  .514  .132  .231   8.2  10.4   9.3   4.6  1.9  0.9  15.9  18.9    -0.2  0.2   0.1    .017    -4.0  -1.3  -5.2  -0.2  2018

In [31]:
# check shape and see if there are any duplicates
print('The shape of the DataFrame is: ', advanced2018.shape)
print('The number of duplicate entries is: ', advanced2018.duplicated().sum())

The shape of the DataFrame is:  (690, 29)
The number of duplicate entries is:  25

In [32]:
# drop duplicated players in advanced stats df
drop_duplicate_players(advanced2018)

                    Player   Pos   Age    Tm     G    MP   PER   TS%  3PAr   FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%         OWS   DWS    WS   WS/48         OBPM  DBPM    BPM  VORP  Year
0             Alex Abrines    SG    24   OKC    75  1134   9.0  .567  .759  .158   2.5   8.9   5.6   3.4   1.7   0.6   7.4  12.7         1.3   1.0   2.2    .094         -0.5  -1.7   -2.2  -0.1  2018
1               Quincy Acy    PF    27   BRK    70  1359   8.2  .525  .800  .164   3.1  17.1  10.0   6.0   1.2   1.6  13.3  14.4        -0.1   1.1   1.0    .036         -2.0  -0.2   -2.2  -0.1  2018
2             Steven Adams     C    24   OKC    76  2487  20.6  .630  .003  .402  16.6  13.9  15.3   5.5   1.8   2.8  13.3  16.7         6.7   3.0   9.7    .187          2.2   1.1    3.3   3.3  2018
3              Bam Adebayo     C    20   MIA    69  1368  15.7  .570  .021  .526   9.7  21.6  15.6  11.0   1.2   2.5  13.6  15.9         2.3   1.9   4.2    .148         -1.6   1.8    0.2   0.8  2018
4            Arron Afflalo    SG    32   ORL    53   682   5.8  .516  .432  .160   0.6  10.1   5.3   6.2   0.3   1.1  10.8  12.5        -0.1   0.2   0.1    .009         -4.1  -1.8   -5.8  -0.7  2018
5             Cole Aldrich     C    29   MIN    21    49   6.0  .340  .000  .400   7.0  28.6  17.6   8.2   2.0   1.8   5.4  16.8        -0.1   0.1   0.0  -0.013         -7.0   0.1   -6.9  -0.1  2018
6        LaMarcus Aldridge     C    32   SAS    75  2509  25.0  .570  .068  .296  10.8  17.3  14.0  11.3   0.9   3.0   6.8  29.1         7.4   3.5  10.9    .209          3.0   0.3    3.3   3.3  2018
7            Jarrett Allen     C    19   BRK    72  1441  17.5  .636  .038  .370  10.5  18.1  14.3   5.4   0.9   4.6  15.1  16.3         2.7   1.5   4.2    .141         -1.3   1.4    0.2   0.8  2018
8             Kadeem Allen    PG    25   BOS    18   107   2.6  .366  .500  .409   4.1   7.1   5.6  15.2   1.4   1.6  25.7  14.6        -0.2   0.1  -0.1  -0.038         -6.7   0.3   -6.4  -0.1  2018
9               Tony Allen    SF    36   NOP    22   273   8.7  .514  .132  .231   8.2  10.4   9.3   4.6   1.9   0.9  15.9  18.9        -0.2   0.2   0.1    .017         -4.0  -1.3   -5.2  -0.2  2018
10         Al-Farouq Aminu    PF    27   POR    69  2072  12.0  .522  .582  .137   5.2  22.3  13.8   5.8   1.9   1.6  11.3  14.8         0.9   3.2   4.2    .097         -0.8   1.9    1.1   1.6  2018
11         Justin Anderson    SF    24   PHI    38   519  13.0  .540  .510  .188   5.4  13.6   9.6   7.1   1.4   1.1   6.8  19.3         0.6   0.7   1.2    .115         -0.5  -1.5   -2.0   0.0  2018
12           Kyle Anderson    SF    24   SAS    74  1978  15.9  .582  .130  .333   4.7  17.6  11.1  14.7   2.9   2.5  15.8  13.5         2.4   3.8   6.2    .151         -0.3   4.3    4.1   3.0  2018
13           Ryan Anderson    PF    29   HOU    66  1725  12.6  .592  .706  .194   6.2  15.4  10.8   5.1   0.7   1.0   7.5  14.4         3.1   1.7   4.8    .132          1.0  -0.8    0.2   1.0  2018
14            Ike Anigbogu     C    19   IND    11    30  21.6  .558  .000  .667  19.0  15.0  16.9   0.0   1.7   8.9  14.7  20.3         0.1   0.0   0.1    .165         -4.1  -1.2   -5.4   0.0  2018
15   Giannis Antetokounmpo    PF    23   MIL    75  2756  27.3  .598  .100  .457   6.7  25.3  16.0  23.7   2.0   3.3  11.7  31.2         8.3   3.6  11.9    .207          3.9   1.9    5.8   5.4  2018
16         Carmelo Anthony    PF    33   OKC    78  2501  12.7  .503  .406  .165   2.9  17.7  10.0   6.5   0.9   1.8   7.3  23.2         1.2   2.5   3.7    .071         -1.9  -1.9   -3.8  -1.1  2018
17              OG Anunoby    SF    20   TOR    74  1481  10.0  .587  .569  .179   3.4  10.4   7.0   5.0   1.7   0.8  10.8  12.4         1.4   1.6   3.0    .098          0.2   0.4    0.6   1.0  2018
18        Ryan Arcidiacono    PG    23   CHI    24   304   7.3  .550  .756  .146   0.3   8.8   4.4  15.5   2.1   0.0  23.0   8.1         0.1   0.2   0.3    .040         -3.3  -0.7   -4.1  -0.2  2018
19            Trevor Ariza    SF    32   HOU    67  2269  11.8  .567  .710  .137   1.7  12.9   7.3   6.8   2.1   0.5   7.0  14.4         2.6   2.8   5.3    .113          0.8   0.7    1.5   2.0  2018
20                    None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None  None    None  None   None  None   None  None  2018
21          Darrell Arthur    PF    29   DEN    19   141   8.4  .559  .489  .064   2.4   9.5   6.0   9.3   2.8   1.8  23.7  19.5        -0.2   0.1   0.0  -0.011         -3.5  -1.0   -4.5  -0.1  2018
22             Jamel Artis    SG    25   ORL    15   279   6.9  .457  .367  .152   1.6  13.5   7.5   9.3   0.4   0.9   8.7  14.5        -0.1   0.1   0.0  -0.006         -4.3  -1.5   -5.9  -0.3  2018
23               Omer Asik     C    31   TOT    18   182   3.1  .397  .000  .591   5.5  22.2  14.0   2.1   0.5   1.9  24.5   8.7        -0.2   0.2  -0.1  -0.021         -8.1   0.0   -8.1  -0.3  2018
26           D.J. Augustin    PG    30   ORL    75  1760  15.4  .615  .504  .350   1.9   8.2   5.0  24.4   1.5   0.0  16.5  18.6         3.3   0.8   4.1    .110          1.5  -2.5   -0.9   0.5  2018
27            Luke Babbitt    SF    28   TOT    50   715   9.8  .576  .726  .102   1.1  13.9   7.5   6.5   0.5   0.8   7.8  15.0         0.5   0.4   0.9    .060         -1.0  -2.2   -3.2  -0.2  2018
30            Dwayne Bacon    SG    22   CHO    53   713   5.8  .431  .224  .130   0.6  18.5   9.4   7.5   1.1   0.2  10.2  13.7        -0.7   0.6  -0.1  -0.007         -5.4  -0.3   -5.7  -0.7  2018
31               Ron Baker    SG    24   NYK    29   385   9.3  .504  .559  .441   1.4   7.2   4.3  15.5   3.3   1.3  20.4  10.0         0.1   0.4   0.5    .059         -1.9   0.9   -1.0   0.1  2018
32            Wade Baldwin    PG    21   POR     7    80  16.6  .748  .238  .476   1.4   9.5   5.5   9.8   1.2   1.0  13.6  16.1         0.2   0.1   0.3    .187          1.1  -1.1    0.0   0.0  2018
33              Lonzo Ball    PG    20   LAL    52  1780  12.5  .444  .523  .126   4.2  17.3  10.8  29.2   2.4   2.0  18.6  17.4        -0.5   2.5   2.0    .053         -0.8   2.5    1.7   1.7  2018
..                     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...     ...   ...    ...   ...    ...   ...   ...
653            Okaro White    PF    25   MIA     6    80   8.9  .577  .688  .188   4.2  11.2   7.7   3.5   0.6   1.1   5.5  10.3         0.1   0.1   0.2    .096         -1.5  -1.3   -2.9   0.0  2018
654       Isaiah Whitehead    PG    22   BRK    16   180  11.5  .530  .209  .221   2.3  13.1   7.7  19.6   2.2   0.8  20.3  28.5        -0.3   0.2  -0.1  -0.035         -4.3  -1.3   -5.6  -0.2  2018
655       Hassan Whiteside     C    28   MIA    54  1364  24.1  .573  .003  .315  14.3  36.6  25.4   6.9   1.4   5.9  12.3  24.7         2.3   3.0   5.3    .187         -2.1   2.3    0.2   0.8  2018
656         Andrew Wiggins    SF    22   MIN    82  2979  13.0  .505  .260  .242   3.1  10.8   6.9   8.2   1.5   1.5   8.8  23.4         0.5   1.6   2.1    .034         -1.1  -1.4   -2.5  -0.4  2018
657            Jacob Wiley    PF    23   BRK     5    33   8.2  .410  .500  .500   6.4  29.2  17.7   8.0   1.5   0.0   0.0   6.4         0.0   0.0   0.1    .094         -3.9   0.9   -3.0   0.0  2018
658         Damien Wilkins    SF    38   IND    19   152   4.9  .405  .462  .103   3.7   8.1   5.9   7.8   0.7   0.6  10.9  13.4        -0.1   0.1  -0.1  -0.019         -4.4  -2.1   -6.5  -0.2  2018
659          Alan Williams    PF    25   PHO     5    70   9.3  .455  .000  .500   4.5  29.5  16.8  16.3   3.4   1.2  24.2  17.5        -0.1   0.1   0.0  -0.004         -6.5   2.8   -3.7   0.0  2018
660          C.J. Williams    SG    27   LAC    38   707   9.5  .512  .396  .081   1.9   6.7   4.4   8.5   2.1   1.5   8.9  13.7         0.3   0.5   0.7    .051         -1.3  -0.1   -1.4   0.1  2018
661       Derrick Williams    PF    26   LAL     2     9  -3.2  .250  .500  .000   0.0  11.7   5.9   0.0   0.0   0.0   0.0  18.9         0.0   0.0   0.0  -0.191        -11.5  -6.6  -18.1   0.0  2018
662           Lou Williams    SG    31   LAC    79  2589  20.2  .574  .387  .367   1.7   6.6   4.2  26.3   1.6   0.6  13.1  29.8         5.5   1.2   6.7    .125          3.8  -2.9    1.0   2.0  2018
664        Marvin Williams    PF    31   CHO    78  2006  13.9  .603  .542  .218   3.9  16.2  10.0   7.0   1.4   1.6   9.7  14.8         3.1   1.9   5.0    .119          1.1   0.5    1.7   1.9  2018
665          Matt Williams    SG    24   MIA     3    11  -0.7  .417  .833  .000   0.0  10.2   5.1   0.0   0.0   0.0  14.3  28.6        -0.1   0.0   0.0  -0.197         -8.5  -8.6  -17.1   0.0  2018
666          Troy Williams    SF    23   TOT    21   307  15.1  .544  .349  .275   8.0  14.8  11.4   7.7   3.2   1.1  13.5  20.1         0.2   0.4   0.5    .085         -0.1   0.2    0.0   0.2  2018
669            D.J. Wilson    PF    21   MIL    22    71  10.3  .622  .313  .125   3.3  13.2   8.3   6.1   2.1   1.2  19.2  13.3         0.0   0.1   0.1    .054         -2.9  -1.2   -4.1   0.0  2018
670           Jamil Wilson    SF    27   LAC    15   274  11.4  .634  .778  .049   1.2  11.5   6.4   5.2   0.9   2.4   8.8  14.3         0.4   0.2   0.5    .096          1.1  -1.1    0.0   0.1  2018
671        Justise Winslow    PF    21   MIA    68  1680  11.5  .496  .264  .213   4.3  20.5  12.4  13.0   1.6   1.7  12.6  16.3         0.2   2.4   2.6    .075         -2.7   1.7   -1.0   0.4  2018
672            Jeff Withey     C    27   DAL     9    39   8.3  .444  .625  .125   2.8  26.6  14.2   0.0   0.0   6.8  10.6  22.0        -0.1   0.1   0.0  -0.054         -9.1  -3.7  -12.8  -0.1  2018
673           Nate Wolters    PG    26   UTA     5    19  -2.9  .167  .000  .000   6.0   5.9   6.0   7.1   0.0   0.0   0.0  14.2        -0.1   0.0  -0.1  -0.137        -10.3  -2.1  -12.4   0.0  2018
674         Brandan Wright    PF    30   TOT    28   381  19.0  .596  .000  .324   9.8  19.3  14.4   5.6   1.7   6.4   6.4  14.7         0.8   0.5   1.3    .163         -1.3   2.2    0.9   0.3  2018
677           Delon Wright    PG    25   TOR    69  1433  16.5  .574  .354  .271   3.6  11.7   7.7  19.6   2.5   1.8  13.9  17.2         2.5   2.1   4.5    .152          1.2   1.6    2.8   1.7  2018
678     Guerschon Yabusele    PF    22   BOS    33   235  12.3  .559  .607  .361   8.0  16.1  12.1  10.0   0.9   1.8  14.5  15.7         0.3   0.3   0.6    .122         -1.0   0.2   -0.7   0.1  2018
679            James Young    SG    22   PHI     6    61   4.6  .511  .714  .429   0.0   3.4   1.8   4.3   0.0   0.0   5.7  12.3         0.0   0.0   0.1    .041         -3.0  -3.6   -6.6  -0.1  2018
680              Joe Young    PG    25   IND    53   558  10.1  .521  .355  .156   2.4  10.3   6.4   9.9   1.3   0.2  11.6  18.0         0.1   0.4   0.5    .043         -2.4  -2.3   -4.7  -0.4  2018
681             Nick Young    SG    32   GSW    80  1393  10.0  .562  .668  .133   1.7   7.9   5.0   3.5   1.3   0.4   7.0  17.5         0.8   0.9   1.7    .059         -0.2  -3.4   -3.7  -0.6  2018
682         Thaddeus Young    PF    29   IND    81  2607  14.8  .528  .209  .106   8.0  14.1  11.1   8.5   2.6   1.2  10.4  17.3         2.3   3.2   5.5    .101          0.1   1.4    1.5   2.3  2018
683            Cody Zeller     C    25   CHO    33   627  15.9  .602  .019  .545  11.4  19.3  15.3   7.4   1.1   2.8  14.6  15.7         1.2   0.7   1.9    .145         -0.6   1.3    0.7   0.4  2018
684           Tyler Zeller     C    28   TOT    66  1109  16.0  .598  .084  .237  11.0  19.4  15.2   6.7   0.7   2.5  11.3  16.4         2.0   0.9   2.9    .126         -1.1  -0.5   -1.6   0.1  2018
687            Paul Zipser    SF    23   CHI    54   824   5.2  .445  .470  .107   1.6  16.0   8.5   8.0   1.2   1.6  14.9  15.2        -1.1   0.6  -0.6  -0.034         -5.5  -0.3   -5.9  -0.8  2018
688             Ante Zizic     C    21   CLE    32   214  24.2  .746  .000  .433  12.8  18.6  15.7   3.8   0.5   5.2  12.1  18.8         0.9   0.2   1.0    .231          1.3  -1.2    0.1   0.1  2018
689            Ivica Zubac     C    20   LAL    43   410  15.3  .557  .008  .418  11.8  20.1  16.0   8.8   0.9   3.0  15.3  17.6         0.5   0.5   1.0    .118         -2.7   0.5   -2.2   0.0  2018

[541 rows x 29 columns]

In [33]:
advanced2018.isnull().sum()

Player    1
Pos       1
Age       1
Tm        1
G         1
MP        1
PER       1
TS%       1
3PAr      1
FTr       1
ORB%      1
DRB%      1
TRB%      1
AST%      1
STL%      1
BLK%      1
TOV%      1
USG%      1
          1
OWS       1
DWS       1
WS        1
WS/48     1
          1
OBPM      1
DBPM      1
BPM       1
VORP      1
Year      0
dtype: int64

In [34]:
# replace 'None' row with 'NaN'
advanced2018.fillna(value=pd.np.nan, inplace = True)

In [35]:
# check to see that 'None' was replaced with 'NaN'
advanced2018.iloc[16:22, :]

              Player  Pos  Age   Tm    G    MP   PER   TS%  3PAr   FTr ORB%  DRB%  TRB%  AST% STL% BLK%  TOV%  USG%        OWS  DWS   WS   WS/48       OBPM  DBPM   BPM  VORP  Year
16   Carmelo Anthony   PF   33  OKC   78  2501  12.7  .503  .406  .165  2.9  17.7  10.0   6.5  0.9  1.8   7.3  23.2        1.2  2.5  3.7    .071       -1.9  -1.9  -3.8  -1.1  2018
17        OG Anunoby   SF   20  TOR   74  1481  10.0  .587  .569  .179  3.4  10.4   7.0   5.0  1.7  0.8  10.8  12.4        1.4  1.6  3.0    .098        0.2   0.4   0.6   1.0  2018
18  Ryan Arcidiacono   PG   23  CHI   24   304   7.3  .550  .756  .146  0.3   8.8   4.4  15.5  2.1  0.0  23.0   8.1        0.1  0.2  0.3    .040       -3.3  -0.7  -4.1  -0.2  2018
19      Trevor Ariza   SF   32  HOU   67  2269  11.8  .567  .710  .137  1.7  12.9   7.3   6.8  2.1  0.5   7.0  14.4        2.6  2.8  5.3    .113        0.8   0.7   1.5   2.0  2018
20               NaN  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN  NaN   NaN  NaN  NaN     NaN  NaN   NaN   NaN   NaN   NaN  2018
21    Darrell Arthur   PF   29  DEN   19   141   8.4  .559  .489  .064  2.4   9.5   6.0   9.3  2.8  1.8  23.7  19.5       -0.2  0.1  0.0  -0.011       -3.5  -1.0  -4.5  -0.1  2018

In [36]:
# pre-drop shape
advanced2018.shape

(541, 29)

In [37]:
# dropna row
advanced2018.dropna(axis=0, inplace=True)

In [38]:
# post-dropna shape
advanced2018.shape

(540, 29)

In [39]:
adv18_cols = pd.Series(data=advanced2018.columns)

adv18_cols

0     Player
1        Pos
2        Age
3         Tm
4          G
5         MP
6        PER
7        TS%
8       3PAr
9        FTr
10      ORB%
11      DRB%
12      TRB%
13      AST%
14      STL%
15      BLK%
16      TOV%
17      USG%
18
19       OWS
20       DWS
21        WS
22     WS/48
23
24      OBPM
25      DBPM
26       BPM
27      VORP
28      Year
dtype: object

So it looks like there are two blank columns at index 18 and 23. Let's drop those.

In [40]:
#4: drop blank columns
advanced2018.drop(advanced2018.columns[[18, 23]], axis=1, inplace = True);

In [41]:
advanced2018.head(10)

              Player Pos Age   Tm   G    MP   PER   TS%  3PAr   FTr  ORB%  DRB%  TRB%  AST% STL% BLK%  TOV%  USG%   OWS  DWS    WS   WS/48  OBPM  DBPM   BPM  VORP  Year
0       Alex Abrines  SG  24  OKC  75  1134   9.0  .567  .759  .158   2.5   8.9   5.6   3.4  1.7  0.6   7.4  12.7   1.3  1.0   2.2    .094  -0.5  -1.7  -2.2  -0.1  2018
1         Quincy Acy  PF  27  BRK  70  1359   8.2  .525  .800  .164   3.1  17.1  10.0   6.0  1.2  1.6  13.3  14.4  -0.1  1.1   1.0    .036  -2.0  -0.2  -2.2  -0.1  2018
2       Steven Adams   C  24  OKC  76  2487  20.6  .630  .003  .402  16.6  13.9  15.3   5.5  1.8  2.8  13.3  16.7   6.7  3.0   9.7    .187   2.2   1.1   3.3   3.3  2018
3        Bam Adebayo   C  20  MIA  69  1368  15.7  .570  .021  .526   9.7  21.6  15.6  11.0  1.2  2.5  13.6  15.9   2.3  1.9   4.2    .148  -1.6   1.8   0.2   0.8  2018
4      Arron Afflalo  SG  32  ORL  53   682   5.8  .516  .432  .160   0.6  10.1   5.3   6.2  0.3  1.1  10.8  12.5  -0.1  0.2   0.1    .009  -4.1  -1.8  -5.8  -0.7  2018
5       Cole Aldrich   C  29  MIN  21    49   6.0  .340  .000  .400   7.0  28.6  17.6   8.2  2.0  1.8   5.4  16.8  -0.1  0.1   0.0  -0.013  -7.0   0.1  -6.9  -0.1  2018
6  LaMarcus Aldridge   C  32  SAS  75  2509  25.0  .570  .068  .296  10.8  17.3  14.0  11.3  0.9  3.0   6.8  29.1   7.4  3.5  10.9    .209   3.0   0.3   3.3   3.3  2018
7      Jarrett Allen   C  19  BRK  72  1441  17.5  .636  .038  .370  10.5  18.1  14.3   5.4  0.9  4.6  15.1  16.3   2.7  1.5   4.2    .141  -1.3   1.4   0.2   0.8  2018
8       Kadeem Allen  PG  25  BOS  18   107   2.6  .366  .500  .409   4.1   7.1   5.6  15.2  1.4  1.6  25.7  14.6  -0.2  0.1  -0.1  -0.038  -6.7   0.3  -6.4  -0.1  2018
9         Tony Allen  SF  36  NOP  22   273   8.7  .514  .132  .231   8.2  10.4   9.3   4.6  1.9  0.9  15.9  18.9  -0.2  0.2   0.1    .017  -4.0  -1.3  -5.2  -0.2  2018

In [42]:
advanced2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 689
Data columns (total 27 columns):
Player    540 non-null object
Pos       540 non-null object
Age       540 non-null object
Tm        540 non-null object
G         540 non-null object
MP        540 non-null object
PER       540 non-null object
TS%       540 non-null object
3PAr      540 non-null object
FTr       540 non-null object
ORB%      540 non-null object
DRB%      540 non-null object
TRB%      540 non-null object
AST%      540 non-null object
STL%      540 non-null object
BLK%      540 non-null object
TOV%      540 non-null object
USG%      540 non-null object
OWS       540 non-null object
DWS       540 non-null object
WS        540 non-null object
WS/48     540 non-null object
OBPM      540 non-null object
DBPM      540 non-null object
BPM       540 non-null object
VORP      540 non-null object
Year      540 non-null int64
dtypes: int64(1), object(26)
memory usage: 118.1+ KB

In [45]:
# convert statistical columns to numerics; first get list of columns to convert
cols_to_numeric = advanced2018.columns.drop(['Player', 'Pos', 'Age', 'Tm', 'Year'])

[Setting With Copy Warning](https://www.dataquest.io/blog/settingwithcopywarning/)

In [46]:
# convert selected columns to numeric dtypes
advanced2018[cols_to_numeric] = advanced2018[cols_to_numeric].apply(pd.to_numeric, errors = 'coerce')

In [47]:
advanced2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 689
Data columns (total 27 columns):
Player    540 non-null object
Pos       540 non-null object
Age       540 non-null object
Tm        540 non-null object
G         540 non-null int64
MP        540 non-null int64
PER       540 non-null float64
TS%       537 non-null float64
3PAr      537 non-null float64
FTr       537 non-null float64
ORB%      540 non-null float64
DRB%      540 non-null float64
TRB%      540 non-null float64
AST%      540 non-null float64
STL%      540 non-null float64
BLK%      540 non-null float64
TOV%      537 non-null float64
USG%      540 non-null float64
OWS       540 non-null float64
DWS       540 non-null float64
WS        540 non-null float64
WS/48     540 non-null float64
OBPM      540 non-null float64
DBPM      540 non-null float64
BPM       540 non-null float64
VORP      540 non-null float64
Year      540 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 118.1+ KB

In [48]:
advanced2018.head(5)

          Player Pos Age   Tm   G    MP   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0   Alex Abrines  SG  24  OKC  75  1134   9.0  0.567  0.759  0.158   2.5   8.9   5.6   3.4   1.7   0.6   7.4  12.7  1.3  1.0  2.2  0.094  -0.5  -1.7 -2.2  -0.1  2018
1     Quincy Acy  PF  27  BRK  70  1359   8.2  0.525  0.800  0.164   3.1  17.1  10.0   6.0   1.2   1.6  13.3  14.4 -0.1  1.1  1.0  0.036  -2.0  -0.2 -2.2  -0.1  2018
2   Steven Adams   C  24  OKC  76  2487  20.6  0.630  0.003  0.402  16.6  13.9  15.3   5.5   1.8   2.8  13.3  16.7  6.7  3.0  9.7  0.187   2.2   1.1  3.3   3.3  2018
3    Bam Adebayo   C  20  MIA  69  1368  15.7  0.570  0.021  0.526   9.7  21.6  15.6  11.0   1.2   2.5  13.6  15.9  2.3  1.9  4.2  0.148  -1.6   1.8  0.2   0.8  2018
4  Arron Afflalo  SG  32  ORL  53   682   5.8  0.516  0.432  0.160   0.6  10.1   5.3   6.2   0.3   1.1  10.8  12.5 -0.1  0.2  0.1  0.009  -4.1  -1.8 -5.8  -0.7  2018

In [49]:
advanced2018.tail(5)

           Player Pos Age   Tm   G    MP   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
683   Cody Zeller   C  25  CHO  33   627  15.9  0.602  0.019  0.545  11.4  19.3  15.3   7.4   1.1   2.8  14.6  15.7  1.2  0.7  1.9  0.145  -0.6   1.3  0.7   0.4  2018
684  Tyler Zeller   C  28  TOT  66  1109  16.0  0.598  0.084  0.237  11.0  19.4  15.2   6.7   0.7   2.5  11.3  16.4  2.0  0.9  2.9  0.126  -1.1  -0.5 -1.6   0.1  2018
687   Paul Zipser  SF  23  CHI  54   824   5.2  0.445  0.470  0.107   1.6  16.0   8.5   8.0   1.2   1.6  14.9  15.2 -1.1  0.6 -0.6 -0.034  -5.5  -0.3 -5.9  -0.8  2018
688    Ante Zizic   C  21  CLE  32   214  24.2  0.746  0.000  0.433  12.8  18.6  15.7   3.8   0.5   5.2  12.1  18.8  0.9  0.2  1.0  0.231   1.3  -1.2  0.1   0.1  2018
689   Ivica Zubac   C  20  LAL  43   410  15.3  0.557  0.008  0.418  11.8  20.1  16.0   8.8   0.9   3.0  15.3  17.6  0.5  0.5  1.0  0.118  -2.7   0.5 -2.2   0.0  2018

In [50]:
advanced2018.reset_index(drop=True, inplace = True);

In [51]:
advanced2018.tail(5)

           Player Pos Age   Tm   G    MP   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
535   Cody Zeller   C  25  CHO  33   627  15.9  0.602  0.019  0.545  11.4  19.3  15.3   7.4   1.1   2.8  14.6  15.7  1.2  0.7  1.9  0.145  -0.6   1.3  0.7   0.4  2018
536  Tyler Zeller   C  28  TOT  66  1109  16.0  0.598  0.084  0.237  11.0  19.4  15.2   6.7   0.7   2.5  11.3  16.4  2.0  0.9  2.9  0.126  -1.1  -0.5 -1.6   0.1  2018
537   Paul Zipser  SF  23  CHI  54   824   5.2  0.445  0.470  0.107   1.6  16.0   8.5   8.0   1.2   1.6  14.9  15.2 -1.1  0.6 -0.6 -0.034  -5.5  -0.3 -5.9  -0.8  2018
538    Ante Zizic   C  21  CLE  32   214  24.2  0.746  0.000  0.433  12.8  18.6  15.7   3.8   0.5   5.2  12.1  18.8  0.9  0.2  1.0  0.231   1.3  -1.2  0.1   0.1  2018
539   Ivica Zubac   C  20  LAL  43   410  15.3  0.557  0.008  0.418  11.8  20.1  16.0   8.8   0.9   3.0  15.3  17.6  0.5  0.5  1.0  0.118  -2.7   0.5 -2.2   0.0  2018

In [52]:
# check shape of new DataFrame
print('The shape of the updated DataFrame is: ', advanced2018.shape)

The shape of the updated DataFrame is:  (540, 27)

In [53]:
advanced2018.to_csv('data/advanced2018.csv')

Cool now we have the per possession and advanced statistics for all the players that played in the NBA during the 2017-2018 season! Now we need to combine them into one dataframe because sometimes 1 is better than 2, at least when it comes to data analysis...

- [How to avoid duplicating columns](https://stackoverflow.com/questions/19125091/pandas-merge-how-to-avoid-duplicating-columns)

Here's an example of what a merge would look like.

In [54]:
pd.merge(left=per_poss2018, right=advanced2018, on='Player').head(10)

              Player Pos_x Age_x Tm_x  G_x  GS  MP_x    FG   FGA    FG%   3P   3PA    3P%    2P   2PA    2P%   FT  FTA    FT%  ORB   DRB   TRB  AST  STL  BLK  TOV    PF   PTS   ORtg  DRtg  Year_x Pos_y Age_y Tm_y  G_y  MP_y   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS    WS  WS/48  OBPM  DBPM  BPM  VORP  Year_y
0       Alex Abrines    SG    24  OKC   75   8  1134   5.0  12.7  0.395  3.7   9.7  0.380   1.4   3.1  0.443  1.7  2.0  0.848  1.1   3.9   5.0  1.2  1.7  0.4  1.1   5.4  15.4  116.0   110    2018    SG    24  OKC   75  1134   9.0  0.567  0.759  0.158   2.5   8.9   5.6   3.4   1.7   0.6   7.4  12.7  1.3  1.0   2.2  0.094  -0.5  -1.7 -2.2  -0.1    2018
1         Quincy Acy    PF    27  BRK   70   8  1359   4.6  13.0  0.356  3.6  10.4  0.349   1.0   2.6  0.384  1.8  2.1  0.817  1.4   7.8   9.2  2.0  1.2  1.0  2.1   5.3  14.7   99.0   110    2018    PF    27  BRK   70  1359   8.2  0.525  0.800  0.164   3.1  17.1  10.0   6.0   1.2   1.6  13.3  14.4 -0.1  1.1   1.0  0.036  -2.0  -0.2 -2.2  -0.1    2018
2       Steven Adams     C    24  OKC   76  76  2487   8.9  14.2  0.629  0.0   0.0  0.000   8.9  14.2  0.631  3.2  5.7  0.559  7.7   6.0  13.7  1.8  1.8  1.6  2.6   4.3  21.1  125.0   107    2018     C    24  OKC   76  2487  20.6  0.630  0.003  0.402  16.6  13.9  15.3   5.5   1.8   2.8  13.3  16.7  6.7  3.0   9.7  0.187   2.2   1.1  3.3   3.3    2018
3        Bam Adebayo     C    20  MIA   69  19  1368   6.4  12.5  0.512  0.0   0.3  0.000   6.4  12.2  0.523  4.7  6.6  0.721  4.3   9.7  14.0  3.7  1.2  1.5  2.4   5.1  17.5  116.0   105    2018     C    20  MIA   69  1368  15.7  0.570  0.021  0.526   9.7  21.6  15.6  11.0   1.2   2.5  13.6  15.9  2.3  1.9   4.2  0.148  -1.6   1.8  0.2   0.8    2018
4      Arron Afflalo    SG    32  ORL   53   3   682   4.7  11.6  0.401  1.9   5.0  0.386   2.7   6.6  0.413  1.6  1.9  0.846  0.3   4.5   4.7  2.2  0.3  0.6  1.5   4.0  12.8   98.0   115    2018    SG    32  ORL   53   682   5.8  0.516  0.432  0.160   0.6  10.1   5.3   6.2   0.3   1.1  10.8  12.5 -0.1  0.2   0.1  0.009  -4.1  -1.8 -5.8  -0.7    2018
5       Cole Aldrich     C    29  MIN   21   0    49   5.1  15.3  0.333  0.0   0.0    NaN   5.1  15.3  0.333  2.0  6.1  0.333  3.1  12.2  15.3  3.1  2.0  1.0  1.0  11.2  12.2   85.0   107    2018     C    29  MIN   21    49   6.0  0.340  0.000  0.400   7.0  28.6  17.6   8.2   2.0   1.8   5.4  16.8 -0.1  0.1   0.0 -0.013  -7.0   0.1 -6.9  -0.1    2018
6  LaMarcus Aldridge     C    32  SAS   75  75  2509  13.8  27.1  0.510  0.5   1.9  0.293  13.3  25.3  0.526  6.7  8.0  0.837  5.0   7.8  12.8  3.1  0.9  1.8  2.2   3.2  34.9  118.0   105    2018     C    32  SAS   75  2509  25.0  0.570  0.068  0.296  10.8  17.3  14.0  11.3   0.9   3.0   6.8  29.1  7.4  3.5  10.9  0.209   3.0   0.3  3.3   3.3    2018
7      Jarrett Allen     C    19  BRK   72  31  1441   7.9  13.4  0.589  0.2   0.5  0.333   7.7  12.9  0.599  3.8  5.0  0.776  4.9   8.2  13.1  1.7  0.9  3.0  2.8   5.0  19.8  119.0   108    2018     C    19  BRK   72  1441  17.5  0.636  0.038  0.370  10.5  18.1  14.3   5.4   0.9   4.6  15.1  16.3  2.7  1.5   4.2  0.141  -1.3   1.4  0.2   0.8    2018
8       Kadeem Allen    PG    25  BOS   18   1   107   2.8  10.3  0.273  0.0   5.1  0.000   2.8   5.1  0.545  3.3  4.2  0.778  1.9   3.3   5.1  5.6  1.4  0.9  4.2   7.0   8.9   78.0   106    2018    PG    25  BOS   18   107   2.6  0.366  0.500  0.409   4.1   7.1   5.6  15.2   1.4   1.6  25.7  14.6 -0.2  0.1  -0.1 -0.038  -6.7   0.3 -6.4  -0.1    2018
9         Tony Allen    SF    36  NOP   22   0   273   7.7  15.9  0.484  0.7   2.1  0.333   7.0  13.8  0.506  1.9  3.7  0.524  3.5   4.7   8.2  1.6  1.9  0.5  3.3   8.6  18.0   95.0   110    2018    SF    36  NOP   22   273   8.7  0.514  0.132  0.231   8.2  10.4   9.3   4.6   1.9   0.9  15.9  18.9 -0.2  0.2   0.1  0.017  -4.0  -1.3 -5.2  -0.2    2018

As you can see the position, age, team, games and minutes played columns were all duplicated (as indicated by a `_x` or `_y`). So, now we'll need to drop those columns to remedy this issue.

In [55]:
# create new dataframe that merges both the per possession and advanced stats dataframes
df_2018 = pd.merge(per_poss2018, advanced2018, left_index=True, right_index=True, how='outer')

# check out head of new df
df_2018.head(5)

        Player_x Pos_x Age_x Tm_x  G_x  GS  MP_x   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg  DRtg  Year_x       Player_y Pos_y Age_y Tm_y  G_y  MP_y   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year_y
0   Alex Abrines    SG    24  OKC   75   8  1134  5.0  12.7  0.395  3.7   9.7  0.380  1.4   3.1  0.443  1.7  2.0  0.848  1.1  3.9   5.0  1.2  1.7  0.4  1.1  5.4  15.4  116.0   110    2018   Alex Abrines    SG    24  OKC   75  1134   9.0  0.567  0.759  0.158   2.5   8.9   5.6   3.4   1.7   0.6   7.4  12.7  1.3  1.0  2.2  0.094  -0.5  -1.7 -2.2  -0.1    2018
1     Quincy Acy    PF    27  BRK   70   8  1359  4.6  13.0  0.356  3.6  10.4  0.349  1.0   2.6  0.384  1.8  2.1  0.817  1.4  7.8   9.2  2.0  1.2  1.0  2.1  5.3  14.7   99.0   110    2018     Quincy Acy    PF    27  BRK   70  1359   8.2  0.525  0.800  0.164   3.1  17.1  10.0   6.0   1.2   1.6  13.3  14.4 -0.1  1.1  1.0  0.036  -2.0  -0.2 -2.2  -0.1    2018
2   Steven Adams     C    24  OKC   76  76  2487  8.9  14.2  0.629  0.0   0.0  0.000  8.9  14.2  0.631  3.2  5.7  0.559  7.7  6.0  13.7  1.8  1.8  1.6  2.6  4.3  21.1  125.0   107    2018   Steven Adams     C    24  OKC   76  2487  20.6  0.630  0.003  0.402  16.6  13.9  15.3   5.5   1.8   2.8  13.3  16.7  6.7  3.0  9.7  0.187   2.2   1.1  3.3   3.3    2018
3    Bam Adebayo     C    20  MIA   69  19  1368  6.4  12.5  0.512  0.0   0.3  0.000  6.4  12.2  0.523  4.7  6.6  0.721  4.3  9.7  14.0  3.7  1.2  1.5  2.4  5.1  17.5  116.0   105    2018    Bam Adebayo     C    20  MIA   69  1368  15.7  0.570  0.021  0.526   9.7  21.6  15.6  11.0   1.2   2.5  13.6  15.9  2.3  1.9  4.2  0.148  -1.6   1.8  0.2   0.8    2018
4  Arron Afflalo    SG    32  ORL   53   3   682  4.7  11.6  0.401  1.9   5.0  0.386  2.7   6.6  0.413  1.6  1.9  0.846  0.3  4.5   4.7  2.2  0.3  0.6  1.5  4.0  12.8   98.0   115    2018  Arron Afflalo    SG    32  ORL   53   682   5.8  0.516  0.432  0.160   0.6  10.1   5.3   6.2   0.3   1.1  10.8  12.5 -0.1  0.2  0.1  0.009  -4.1  -1.8 -5.8  -0.7    2018

In [56]:
# drop duplicate columns
df_2018.drop(labels = ['Year_x', 'Player_y', 'Pos_y', 'Age_y', 'Tm_y', 'G_y', 'MP_y'], axis = 1, inplace = True);

In [57]:
# remove leftover '_x' or '_y' from any of the columns left
df_2018.columns = df_2018.columns.str.replace('_x', '').str.replace('_y', '')

In [58]:
df_2018.head(5)

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0   Alex Abrines  SG  24  OKC  75   8  1134  5.0  12.7  0.395  3.7   9.7  0.380  1.4   3.1  0.443  1.7  2.0  0.848  1.1  3.9   5.0  1.2  1.7  0.4  1.1  5.4  15.4  116.0   110   9.0  0.567  0.759  0.158   2.5   8.9   5.6   3.4   1.7   0.6   7.4  12.7  1.3  1.0  2.2  0.094  -0.5  -1.7 -2.2  -0.1  2018
1     Quincy Acy  PF  27  BRK  70   8  1359  4.6  13.0  0.356  3.6  10.4  0.349  1.0   2.6  0.384  1.8  2.1  0.817  1.4  7.8   9.2  2.0  1.2  1.0  2.1  5.3  14.7   99.0   110   8.2  0.525  0.800  0.164   3.1  17.1  10.0   6.0   1.2   1.6  13.3  14.4 -0.1  1.1  1.0  0.036  -2.0  -0.2 -2.2  -0.1  2018
2   Steven Adams   C  24  OKC  76  76  2487  8.9  14.2  0.629  0.0   0.0  0.000  8.9  14.2  0.631  3.2  5.7  0.559  7.7  6.0  13.7  1.8  1.8  1.6  2.6  4.3  21.1  125.0   107  20.6  0.630  0.003  0.402  16.6  13.9  15.3   5.5   1.8   2.8  13.3  16.7  6.7  3.0  9.7  0.187   2.2   1.1  3.3   3.3  2018
3    Bam Adebayo   C  20  MIA  69  19  1368  6.4  12.5  0.512  0.0   0.3  0.000  6.4  12.2  0.523  4.7  6.6  0.721  4.3  9.7  14.0  3.7  1.2  1.5  2.4  5.1  17.5  116.0   105  15.7  0.570  0.021  0.526   9.7  21.6  15.6  11.0   1.2   2.5  13.6  15.9  2.3  1.9  4.2  0.148  -1.6   1.8  0.2   0.8  2018
4  Arron Afflalo  SG  32  ORL  53   3   682  4.7  11.6  0.401  1.9   5.0  0.386  2.7   6.6  0.413  1.6  1.9  0.846  0.3  4.5   4.7  2.2  0.3  0.6  1.5  4.0  12.8   98.0   115   5.8  0.516  0.432  0.160   0.6  10.1   5.3   6.2   0.3   1.1  10.8  12.5 -0.1  0.2  0.1  0.009  -4.1  -1.8 -5.8  -0.7  2018

In [59]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 539
Data columns (total 51 columns):
Player    540 non-null object
Pos       540 non-null object
Age       540 non-null object
Tm        540 non-null object
G         540 non-null int64
GS        540 non-null int64
MP        540 non-null int64
FG        540 non-null float64
FGA       540 non-null float64
FG%       537 non-null float64
3P        540 non-null float64
3PA       540 non-null float64
3P%       491 non-null float64
2P        540 non-null float64
2PA       540 non-null float64
2P%       527 non-null float64
FT        540 non-null float64
FTA       540 non-null float64
FT%       501 non-null float64
ORB       540 non-null float64
DRB       540 non-null float64
TRB       540 non-null float64
AST       540 non-null float64
STL       540 non-null float64
BLK       540 non-null float64
TOV       540 non-null float64
PF        540 non-null float64
PTS       540 non-null float64
ORtg      538 non-null float64
DRtg      540 non-null int64
PER       540 non-null float64
TS%       537 non-null float64
3PAr      537 non-null float64
FTr       537 non-null float64
ORB%      540 non-null float64
DRB%      540 non-null float64
TRB%      540 non-null float64
AST%      540 non-null float64
STL%      540 non-null float64
BLK%      540 non-null float64
TOV%      537 non-null float64
USG%      540 non-null float64
OWS       540 non-null float64
DWS       540 non-null float64
WS        540 non-null float64
WS/48     540 non-null float64
OBPM      540 non-null float64
DBPM      540 non-null float64
BPM       540 non-null float64
VORP      540 non-null float64
Year      540 non-null int64
dtypes: float64(42), int64(5), object(4)
memory usage: 239.4+ KB

Awesome! Everything looks good so far. There are no duplicate columns but we need to check to make sure the merge was successful, i.e. it merged horizontally based on the `Player` column.

In [60]:
print('The shape of the new combined dataframe is: ', df_2018.shape)

The shape of the new combined dataframe is:  (540, 51)

In [61]:
print('Do all three DataFrames have the same number of rows? ', 
      per_poss2018.shape[0] == df_2018.shape[0] == advanced2018.shape[0])

Do all three DataFrames have the same number of rows?  True

In [62]:
# export merged df to csv
df_2018.to_csv('data/df_2018')

# Data Wrangling: 2017

In [63]:
# scrap per_poss and advanced stats for year 2017
per_poss2017 = basketball_reference_scrap(2017, 'per_poss')
advanced2017 = basketball_reference_scrap(2017, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2017.shape, 'Advanced: ', advanced2017.shape)

Shape of original DataFrames, Per_poss:  (619, 32) Advanced:  (619, 29)

In [64]:
# function that cleans per possession data from web scrape

def clean_per_poss(df):
    '''function that accepts raw per possession data and cleans it into usable DataFrame'''
    # 1: drop duplicate players
    drop_duplicate_players(df)
    # 2: replace 'None' rows with 'NaN'
    df.fillna(value=pd.np.nan, inplace = True)
    # 3: drop rows with na
    df.dropna(axis = 0, inplace = True)
    # 4: drop blank column
    df.drop(labels = '', axis = 1, inplace = True)
    # 5: variable that contains columns to convert to numerics
    cols_to_numeric = df.columns.drop(['Player', 'Pos', 'Age', 'Tm', 'Year'])
    # 6: convert selected columns to numeric dtypes
    df[cols_to_numeric] = df[cols_to_numeric].apply(pd.to_numeric, errors = 'coerce')
    # 7: reset index
    df.reset_index(drop = True, inplace = True)
    return df

In [65]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2017);

In [66]:
per_poss2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 31 columns):
Player    486 non-null object
Pos       486 non-null object
Age       486 non-null object
Tm        486 non-null object
G         486 non-null int64
GS        486 non-null int64
MP        486 non-null int64
FG        486 non-null float64
FGA       486 non-null float64
FG%       485 non-null float64
3P        486 non-null float64
3PA       486 non-null float64
3P%       450 non-null float64
2P        486 non-null float64
2PA       486 non-null float64
2P%       484 non-null float64
FT        486 non-null float64
FTA       486 non-null float64
FT%       471 non-null float64
ORB       486 non-null float64
DRB       486 non-null float64
TRB       486 non-null float64
AST       486 non-null float64
STL       486 non-null float64
BLK       486 non-null float64
TOV       486 non-null float64
PF        486 non-null float64
PTS       486 non-null float64
ORtg      485 non-null float64
DRtg      486 non-null int64
Year      486 non-null int64
dtypes: float64(22), int64(5), object(4)
memory usage: 117.8+ KB

In [67]:
# function that cleans raw advanced stats pulled from web scrape 

def clean_advanced(df):
    '''function that takes in raw advanced data and cleans it into usable DataFrame'''
    #1: drop duplicate players
    drop_duplicate_players(df)
    #2: replace 'None' row with 'NaN'
    df.fillna(value=pd.np.nan, inplace = True)
    #3: dropna row
    df.dropna(axis=0, inplace=True)
    #4: drop blank columns
    df.drop(df.columns[[18, 23]], axis=1, inplace = True)
    #7: create list of columns to convert to numerics
    cols_to_numeric = df.columns.drop(['Player', 'Pos', 'Age', 'Tm', 'Year'])
    #8: convert selected columns to numeric dtypes
    df[cols_to_numeric] = df[cols_to_numeric].apply(pd.to_numeric, errors = 'coerce')
    #9: reset_index
    df.reset_index(drop=True, inplace=True)
    #9: return updated df
    return df

In [68]:
# clean up advanced 2017 stats
clean_advanced(advanced2017);

In [69]:
advanced2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 27 columns):
Player    486 non-null object
Pos       486 non-null object
Age       486 non-null object
Tm        486 non-null object
G         486 non-null int64
MP        486 non-null int64
PER       486 non-null float64
TS%       485 non-null float64
3PAr      485 non-null float64
FTr       485 non-null float64
ORB%      486 non-null float64
DRB%      486 non-null float64
TRB%      486 non-null float64
AST%      486 non-null float64
STL%      486 non-null float64
BLK%      486 non-null float64
TOV%      485 non-null float64
USG%      486 non-null float64
OWS       486 non-null float64
DWS       486 non-null float64
WS        486 non-null float64
WS/48     486 non-null float64
OBPM      486 non-null float64
DBPM      486 non-null float64
BPM       486 non-null float64
VORP      486 non-null float64
Year      486 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 102.6+ KB

In [70]:
# function to merge and clean per possession and advanced dataframe

def merge_df(df1, df2):
    '''function to merge clean per_poss and advanced dataframe'''
    #1: merge df1 and df2
    df = pd.merge(df1, df2, left_index=True, right_index=True, how='outer')
    #2: drop duplicate columns
    df.drop(labels = ['Year_x', 'Player_y', 'Pos_y', 'Age_y', 'Tm_y', 'G_y', 'MP_y'], axis = 1, inplace = True)
    #3: replace columns that still have '_x' and '_y'
    df.columns = df.columns.str.replace('_x', '').str.replace('_y', '')
    #4: print to confirm that all three df's have same number of rows
    print('Do all three DataFrames have the same number of rows? ',
         df1.shape[0] == df2.shape[0] == df.shape[0])
    #5: return merged df
    return df

In [71]:
df_2017 = merge_df(per_poss2017, advanced2017)

df_2017.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB   DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0   Alex Abrines  SG  23  OKC  68   6  1055  6.2  15.9  0.393  4.4  11.5  0.381  1.9   4.4  0.426  2.0  2.3  0.898  0.8   3.2   4.0  1.9  1.7  0.4  1.5  5.3  18.9  113.0   110  10.1  0.560  0.724  0.144   1.9   7.1   4.5   5.5   1.7   0.6   8.3  15.9  1.2  0.9  2.1  0.096  -0.3  -2.2 -2.5  -0.1  2017
1     Quincy Acy  PF  26  TOT  38   1   558  6.0  14.6  0.412  3.2   7.7  0.411  2.8   6.8  0.413  3.9  5.1  0.750  1.7   8.1   9.8  1.5  1.2  1.3  1.8  5.7  19.0  109.0   110  11.8  0.565  0.529  0.353   3.9  18.0  11.0   4.9   1.2   2.0   9.7  16.8  0.5  0.5  0.9  0.082  -1.8  -1.2 -3.0  -0.1  2017
2   Steven Adams   C  23  OKC  80  80  2389  7.7  13.5  0.571  0.0   0.0  0.000  7.7  13.4  0.572  3.2  5.3  0.611  5.8   6.8  12.6  1.8  1.8  1.6  3.0  4.0  18.6  114.0   107  16.5  0.589  0.002  0.392  13.0  15.4  14.2   5.4   1.8   2.6  16.0  16.2  3.3  3.1  6.5  0.130  -0.7   1.2  0.6   1.5  2017
3  Arron Afflalo  SG  31  SAC  61  45  1580  5.9  13.5  0.440  2.0   4.8  0.411  3.9   8.6  0.457  2.7  3.0  0.892  0.3   3.7   4.0  2.5  0.7  0.2  1.3  3.3  16.5  109.0   116   8.9  0.559  0.360  0.221   0.7   8.4   4.6   7.4   0.7   0.3   8.4  14.4  1.2  0.2  1.4  0.043  -1.4  -2.1 -3.5  -0.6  2017
4  Alexis Ajinca   C  28  NOP  39  15   584  7.5  14.9  0.500  0.0   0.3  0.000  7.5  14.6  0.511  2.4  3.4  0.725  3.9  11.0  14.8  1.0  1.7  1.8  2.6  6.5  17.4  101.0   104  12.9  0.529  0.022  0.225   8.3  23.8  16.0   3.1   1.7   3.1  13.7  17.2  0.0  0.9  1.0  0.080  -5.1   1.0 -4.1  -0.3  2017

In [72]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 486 entries, 0 to 485
Data columns (total 51 columns):
Player    486 non-null object
Pos       486 non-null object
Age       486 non-null object
Tm        486 non-null object
G         486 non-null int64
GS        486 non-null int64
MP        486 non-null int64
FG        486 non-null float64
FGA       486 non-null float64
FG%       485 non-null float64
3P        486 non-null float64
3PA       486 non-null float64
3P%       450 non-null float64
2P        486 non-null float64
2PA       486 non-null float64
2P%       484 non-null float64
FT        486 non-null float64
FTA       486 non-null float64
FT%       471 non-null float64
ORB       486 non-null float64
DRB       486 non-null float64
TRB       486 non-null float64
AST       486 non-null float64
STL       486 non-null float64
BLK       486 non-null float64
TOV       486 non-null float64
PF        486 non-null float64
PTS       486 non-null float64
ORtg      485 non-null float64
DRtg      486 non-null int64
PER       486 non-null float64
TS%       485 non-null float64
3PAr      485 non-null float64
FTr       485 non-null float64
ORB%      486 non-null float64
DRB%      486 non-null float64
TRB%      486 non-null float64
AST%      486 non-null float64
STL%      486 non-null float64
BLK%      486 non-null float64
TOV%      485 non-null float64
USG%      486 non-null float64
OWS       486 non-null float64
DWS       486 non-null float64
WS        486 non-null float64
WS/48     486 non-null float64
OBPM      486 non-null float64
DBPM      486 non-null float64
BPM       486 non-null float64
VORP      486 non-null float64
Year      486 non-null int64
dtypes: float64(42), int64(5), object(4)
memory usage: 217.4+ KB

As we can see above, there are a few missing values in some of the columns like `3P%` and `FT%`; I'm not too worried about this right now because these are most likely due to players that did not make a three point shot or a free throw, thus their percentage would be `0` which is a quick fix once we get all the seasons together.

In [73]:
# export merged df to csv
df_2017.to_csv('data/df_2017')

# Data Wrangling: 2016

In [74]:
# scrape per_poss and advanced stats for year 2016
per_poss2016 = basketball_reference_scrap(2016, 'per_poss')
advanced2016 = basketball_reference_scrap(2016, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2016.shape, 'Advanced: ', advanced2016.shape)

Shape of original DataFrames, Per_poss:  (601, 32) Advanced:  (601, 29)

In [75]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2016);

In [76]:
per_poss2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476 entries, 0 to 475
Data columns (total 31 columns):
Player    476 non-null object
Pos       476 non-null object
Age       476 non-null object
Tm        476 non-null object
G         476 non-null int64
GS        476 non-null int64
MP        476 non-null int64
FG        476 non-null float64
FGA       476 non-null float64
FG%       475 non-null float64
3P        476 non-null float64
3PA       476 non-null float64
3P%       433 non-null float64
2P        476 non-null float64
2PA       476 non-null float64
2P%       473 non-null float64
FT        476 non-null float64
FTA       476 non-null float64
FT%       462 non-null float64
ORB       476 non-null float64
DRB       476 non-null float64
TRB       476 non-null float64
AST       476 non-null float64
STL       476 non-null float64
BLK       476 non-null float64
TOV       476 non-null float64
PF        476 non-null float64
PTS       476 non-null float64
ORtg      475 non-null float64
DRtg      476 non-null int64
Year      476 non-null int64
dtypes: float64(22), int64(5), object(4)
memory usage: 115.4+ KB

In [77]:
# clean up advanced 2016 stats
clean_advanced(advanced2016);

In [78]:
advanced2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476 entries, 0 to 475
Data columns (total 27 columns):
Player    476 non-null object
Pos       476 non-null object
Age       476 non-null object
Tm        476 non-null object
G         476 non-null int64
MP        476 non-null int64
PER       476 non-null float64
TS%       475 non-null float64
3PAr      475 non-null float64
FTr       475 non-null float64
ORB%      476 non-null float64
DRB%      476 non-null float64
TRB%      476 non-null float64
AST%      476 non-null float64
STL%      476 non-null float64
BLK%      476 non-null float64
TOV%      475 non-null float64
USG%      476 non-null float64
OWS       476 non-null float64
DWS       476 non-null float64
WS        476 non-null float64
WS/48     476 non-null float64
OBPM      476 non-null float64
DBPM      476 non-null float64
BPM       476 non-null float64
VORP      476 non-null float64
Year      476 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 100.5+ KB

In [79]:
print('Shape of new DataFrames, Per_poss: ', per_poss2016.shape, 'Advanced: ', advanced2016.shape)

Shape of new DataFrames, Per_poss:  (476, 31) Advanced:  (476, 27)

In [80]:
df_2016 = merge_df(per_poss2016, advanced2016)

df_2016.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%    FT   FTA    FT%  ORB   DRB   TRB   AST   STL  BLK  TOV   PF   PTS   ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0     Quincy Acy  PF  25  SAC  59  29   876  6.5  11.7  0.556  1.0  2.7  0.388  5.5   9.0  0.606   2.7   3.7  0.735  3.6   6.7  10.3   1.5   1.6  1.3  1.5  5.6  16.8  124.0   108  14.7  0.629  0.229  0.318   8.1  15.1  11.6   4.4   1.6   2.2  10.0  13.1  1.8  0.7  2.5  0.137   0.2   0.0  0.2   0.5  2016
1   Jordan Adams  SG  21  MEM   2   0    15  6.9  20.6  0.333  0.0  3.4  0.000  6.9  17.2  0.400  10.3  17.2  0.600  0.0   6.9   6.9  10.3  10.3  0.0  6.9  6.9  24.0   84.0    90  17.3  0.427  0.167  0.833   0.0  15.9   7.6  31.9  10.3   0.0  19.6  30.5  0.0  0.0  0.0  0.015  -2.9   4.8  1.9   0.0  2016
2   Steven Adams   C  22  OKC  80  80  2014  6.4  10.5  0.613  0.0  0.0    NaN  6.4  10.5  0.613   2.8   4.8  0.582  5.4   7.7  13.1   1.5   1.0  2.2  2.1  5.5  15.7  123.0   105  15.5  0.621  0.000  0.460  12.5  16.1  14.4   4.3   1.0   3.3  14.1  12.6  4.2  2.3  6.5  0.155   0.8   1.3  2.1   2.1  2016
3  Arron Afflalo  SG  30  NYK  71  57  2371  7.7  17.3  0.443  2.0  5.2  0.382  5.7  12.2  0.469   2.4   2.8  0.840  0.5   5.3   5.8   3.1   0.5  0.2  1.8  3.1  19.7  105.0   112  10.9  0.531  0.298  0.164   1.1  11.0   6.1   9.9   0.5   0.3   8.7  17.9  1.8  0.9  2.7  0.055  -0.6  -1.8 -2.4  -0.2  2016
4  Alexis Ajinca   C  27  NOP  59  17   861  8.6  18.1  0.476  0.0  0.1  0.000  8.6  18.1  0.478   3.0   3.6  0.839  4.3  11.2  15.5   1.8   1.1  2.1  3.1  7.7  20.3  100.0   107  13.8  0.514  0.003  0.197   9.3  25.9  17.3   5.8   1.1   3.4  13.6  20.4  0.2  0.9  1.0  0.058  -4.3  -0.2 -4.5  -0.5  2016

In [81]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476 entries, 0 to 475
Data columns (total 51 columns):
Player    476 non-null object
Pos       476 non-null object
Age       476 non-null object
Tm        476 non-null object
G         476 non-null int64
GS        476 non-null int64
MP        476 non-null int64
FG        476 non-null float64
FGA       476 non-null float64
FG%       475 non-null float64
3P        476 non-null float64
3PA       476 non-null float64
3P%       433 non-null float64
2P        476 non-null float64
2PA       476 non-null float64
2P%       473 non-null float64
FT        476 non-null float64
FTA       476 non-null float64
FT%       462 non-null float64
ORB       476 non-null float64
DRB       476 non-null float64
TRB       476 non-null float64
AST       476 non-null float64
STL       476 non-null float64
BLK       476 non-null float64
TOV       476 non-null float64
PF        476 non-null float64
PTS       476 non-null float64
ORtg      475 non-null float64
DRtg      476 non-null int64
PER       476 non-null float64
TS%       475 non-null float64
3PAr      475 non-null float64
FTr       475 non-null float64
ORB%      476 non-null float64
DRB%      476 non-null float64
TRB%      476 non-null float64
AST%      476 non-null float64
STL%      476 non-null float64
BLK%      476 non-null float64
TOV%      475 non-null float64
USG%      476 non-null float64
OWS       476 non-null float64
DWS       476 non-null float64
WS        476 non-null float64
WS/48     476 non-null float64
OBPM      476 non-null float64
DBPM      476 non-null float64
BPM       476 non-null float64
VORP      476 non-null float64
Year      476 non-null int64
dtypes: float64(42), int64(5), object(4)
memory usage: 213.4+ KB

In [82]:
# export merged df to csv
df_2016.to_csv('data/df_2016')

# Data Wrangling: 2015

In [83]:
# scrape per_poss and advanced stats for year 2015
per_poss2015 = basketball_reference_scrap(2015, 'per_poss')
advanced2015 = basketball_reference_scrap(2015, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2015.shape, 'Advanced: ', advanced2015.shape)

Shape of original DataFrames, Per_poss:  (675, 32) Advanced:  (675, 29)

In [84]:
clean_per_poss(per_poss2015);

In [85]:
per_poss2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 31 columns):
Player    492 non-null object
Pos       492 non-null object
Age       492 non-null object
Tm        492 non-null object
G         492 non-null int64
GS        492 non-null int64
MP        492 non-null int64
FG        492 non-null float64
FGA       492 non-null float64
FG%       490 non-null float64
3P        492 non-null float64
3PA       492 non-null float64
3P%       425 non-null float64
2P        492 non-null float64
2PA       492 non-null float64
2P%       488 non-null float64
FT        492 non-null float64
FTA       492 non-null float64
FT%       475 non-null float64
ORB       492 non-null float64
DRB       492 non-null float64
TRB       492 non-null float64
AST       492 non-null float64
STL       492 non-null float64
BLK       492 non-null float64
TOV       492 non-null float64
PF        492 non-null float64
PTS       492 non-null float64
ORtg      492 non-null int64
DRtg      492 non-null int64
Year      492 non-null int64
dtypes: float64(21), int64(6), object(4)
memory usage: 119.2+ KB

In [86]:
clean_advanced(advanced2015);

In [87]:
advanced2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 27 columns):
Player    492 non-null object
Pos       492 non-null object
Age       492 non-null object
Tm        492 non-null object
G         492 non-null int64
MP        492 non-null int64
PER       492 non-null float64
TS%       490 non-null float64
3PAr      490 non-null float64
FTr       490 non-null float64
ORB%      492 non-null float64
DRB%      492 non-null float64
TRB%      492 non-null float64
AST%      492 non-null float64
STL%      492 non-null float64
BLK%      492 non-null float64
TOV%      491 non-null float64
USG%      492 non-null float64
OWS       492 non-null float64
DWS       492 non-null float64
WS        492 non-null float64
WS/48     492 non-null float64
OBPM      492 non-null float64
DBPM      492 non-null float64
BPM       492 non-null float64
VORP      492 non-null float64
Year      492 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 103.9+ KB

In [88]:
print('Shape of new DataFrames, Per_poss: ', per_poss2015.shape, 'Advanced: ', advanced2015.shape)

Shape of new DataFrames, Per_poss:  (492, 31) Advanced:  (492, 27)

In [89]:
df_2015 = merge_df(per_poss2015, advanced2015)

df_2015.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB   DRB   TRB  AST  STL  BLK  TOV   PF   PTS  ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0     Quincy Acy  PF  24  NYK  68  22  1287  6.2  13.5  0.459  0.7  2.5  0.300  5.5  11.1  0.494  3.1  4.0  0.784  3.2   9.1  12.3  2.8  1.1  0.9  2.5  6.0  16.3   105   109  11.9  0.533  0.181  0.293   6.9  20.5  13.5   8.7   1.1   1.4  13.8  15.5  1.0  0.7  1.7  0.063  -2.3  -0.8 -3.1  -0.3  2015
1   Jordan Adams  SG  20  MEM  30   0   248  7.4  18.1  0.407  2.1  5.3  0.400  5.3  12.8  0.410  2.9  4.8  0.609  1.9   4.0   5.9  3.4  3.4  1.5  2.9  5.1  19.8    96   100  12.8  0.489  0.291  0.267   4.2   8.7   6.4  10.1   3.4   2.3  12.7  20.4  0.0  0.4  0.4  0.073  -1.8   1.2 -0.6   0.1  2015
2   Steven Adams   C  21  OKC  70  67  1771  6.1  11.3  0.544  0.0  0.1  0.000  6.1  11.2  0.547  2.9  5.8  0.502  5.6   9.2  14.8  1.9  1.1  2.4  2.8  6.3  15.2   108   104  14.1  0.549  0.005  0.514  12.2  19.3  15.8   5.5   1.1   3.8  16.8  14.3  1.9  2.2  4.1  0.111  -1.4   1.8  0.4   1.1  2015
3    Jeff Adrien  PF  28  MIN  17   0   215  4.5  10.4  0.432  0.0  0.0    NaN  4.5  10.4  0.432  5.2  9.0  0.579  5.4  12.8  18.2  3.5  0.9  2.1  2.1  7.1  14.2   109   108  14.2  0.494  0.000  0.864  11.9  29.6  20.5  10.5   0.9   3.3  12.9  14.3  0.2  0.2  0.4  0.087  -2.7   0.5 -2.2   0.0  2015
4  Arron Afflalo  SG  29  TOT  78  72  2502  7.5  17.8  0.424  2.4  6.7  0.354  5.2  11.1  0.466  3.4  4.0  0.843  0.5   4.4   5.0  2.6  0.8  0.1  2.3  3.4  20.8   103   111  10.7  0.533  0.377  0.224   1.1   9.7   5.3   8.2   0.8   0.2  10.7  19.0  1.6  1.0  2.6  0.050  -0.5  -1.3 -1.8   0.1  2015

In [90]:
df_2015.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 492 entries, 0 to 491
Data columns (total 51 columns):
Player    492 non-null object
Pos       492 non-null object
Age       492 non-null object
Tm        492 non-null object
G         492 non-null int64
GS        492 non-null int64
MP        492 non-null int64
FG        492 non-null float64
FGA       492 non-null float64
FG%       490 non-null float64
3P        492 non-null float64
3PA       492 non-null float64
3P%       425 non-null float64
2P        492 non-null float64
2PA       492 non-null float64
2P%       488 non-null float64
FT        492 non-null float64
FTA       492 non-null float64
FT%       475 non-null float64
ORB       492 non-null float64
DRB       492 non-null float64
TRB       492 non-null float64
AST       492 non-null float64
STL       492 non-null float64
BLK       492 non-null float64
TOV       492 non-null float64
PF        492 non-null float64
PTS       492 non-null float64
ORtg      492 non-null int64
DRtg      492 non-null int64
PER       492 non-null float64
TS%       490 non-null float64
3PAr      490 non-null float64
FTr       490 non-null float64
ORB%      492 non-null float64
DRB%      492 non-null float64
TRB%      492 non-null float64
AST%      492 non-null float64
STL%      492 non-null float64
BLK%      492 non-null float64
TOV%      491 non-null float64
USG%      492 non-null float64
OWS       492 non-null float64
DWS       492 non-null float64
WS        492 non-null float64
WS/48     492 non-null float64
OBPM      492 non-null float64
DBPM      492 non-null float64
BPM       492 non-null float64
VORP      492 non-null float64
Year      492 non-null int64
dtypes: float64(41), int64(6), object(4)
memory usage: 219.9+ KB

In [91]:
df_2015.to_csv('data/df_2015.csv')

## LEFT OFF HERE (3/31) FINISH WRANGLING FOR 2014 ONWARD

# Data Wrangling: 2014

In [92]:
# scrape per_poss and advanced stats for year 2014
per_poss2014 = basketball_reference_scrap(2014, 'per_poss')
advanced2014 = basketball_reference_scrap(2014, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2014.shape, 'Advanced: ', advanced2014.shape)

Shape of original DataFrames, Per_poss:  (635, 32) Advanced:  (635, 29)

In [93]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2014);

In [94]:
# check results of cleaning function for per possession stats
per_poss2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 31 columns):
Player    481 non-null object
Pos       481 non-null object
Age       481 non-null object
Tm        481 non-null object
G         481 non-null int64
GS        481 non-null int64
MP        481 non-null int64
FG        481 non-null float64
FGA       481 non-null float64
FG%       479 non-null float64
3P        481 non-null float64
3PA       481 non-null float64
3P%       414 non-null float64
2P        481 non-null float64
2PA       481 non-null float64
2P%       478 non-null float64
FT        481 non-null float64
FTA       481 non-null float64
FT%       461 non-null float64
ORB       481 non-null float64
DRB       481 non-null float64
TRB       481 non-null float64
AST       481 non-null float64
STL       481 non-null float64
BLK       481 non-null float64
TOV       481 non-null float64
PF        481 non-null float64
PTS       481 non-null float64
ORtg      480 non-null float64
DRtg      481 non-null int64
Year      481 non-null int64
dtypes: float64(22), int64(5), object(4)
memory usage: 116.6+ KB

In [95]:
# clean up advanced 2014 stats
clean_advanced(advanced2014);

In [96]:
# check results of cleaning function for advanced stats
advanced2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 27 columns):
Player    481 non-null object
Pos       481 non-null object
Age       481 non-null object
Tm        481 non-null object
G         481 non-null int64
MP        481 non-null int64
PER       481 non-null float64
TS%       479 non-null float64
3PAr      479 non-null float64
FTr       479 non-null float64
ORB%      481 non-null float64
DRB%      481 non-null float64
TRB%      481 non-null float64
AST%      481 non-null float64
STL%      481 non-null float64
BLK%      481 non-null float64
TOV%      480 non-null float64
USG%      481 non-null float64
OWS       481 non-null float64
DWS       481 non-null float64
WS        481 non-null float64
WS/48     481 non-null float64
OBPM      481 non-null float64
DBPM      481 non-null float64
BPM       481 non-null float64
VORP      481 non-null float64
Year      481 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 101.5+ KB

In [97]:
# check out new shape of each dataframe
print('Shape of new DataFrames, Per_poss: ', per_poss2014.shape, 'Advanced: ', advanced2014.shape)

Shape of new DataFrames, Per_poss:  (481, 31) Advanced:  (481, 27)

In [98]:
# merge the two dataframes
df_2014 = merge_df(per_poss2014, advanced2014)

df_2014.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB   DRB   TRB  AST  STL  BLK  TOV    PF   PTS   ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0     Quincy Acy  SF  23  TOT  63   0   847  4.0   8.5  0.468  0.2  0.9  0.267  3.7   7.6  0.492  2.1  3.2  0.660  4.3   8.7  13.0  1.7  1.4  1.6  1.8   7.3  10.3  109.0   107  10.1  0.520  0.106  0.376   9.5  19.5  14.4   4.9   1.4   2.5  15.4  10.1  0.6  0.9  1.5  0.086  -2.5   1.4 -1.1   0.2  2014
1   Steven Adams   C  20  OKC  81  20  1197  3.9   7.8  0.503  0.0  0.0    NaN  3.9   7.8  0.503  3.3  5.7  0.581  6.0   8.0  13.9  1.8  1.7  2.4  3.0   8.5  11.1  108.0   102  11.2  0.541  0.000  0.735  14.1  17.1  15.6   4.9   1.7   3.9  22.5  11.7  0.9  1.9  2.9  0.114  -2.1   2.4  0.3   0.7  2014
2    Jeff Adrien  PF  27  TOT  53  12   961  7.8  14.9  0.520  0.0  0.0    NaN  7.8  14.9  0.520  4.1  6.5  0.639  5.5  11.1  16.6  2.1  1.3  2.0  2.1   5.9  19.7  114.0   106  17.4  0.553  0.000  0.433  11.8  24.8  18.2   6.8   1.3   3.0  10.6  17.3  1.6  1.1  2.7  0.134  -1.4   0.3 -1.1   0.2  2014
3  Arron Afflalo  SG  28  ORL  73  73  2552  9.3  20.3  0.459  2.6  6.0  0.427  6.7  14.3  0.473  5.5  6.7  0.815  0.6   4.6   5.3  5.0  0.7  0.1  2.9   2.7  26.7  110.0   112  16.0  0.574  0.297  0.332   1.4  10.2   5.8  16.9   0.7   0.1  11.2  23.3  4.3  1.0  5.3  0.099   1.7  -2.3 -0.6   0.9  2014
4  Alexis Ajinca   C  25  NOP  56  30   951  7.4  13.6  0.546  0.0  0.1  0.000  7.4  13.6  0.548  3.1  3.7  0.836  5.1  10.0  15.2  2.2  1.3  2.5  3.4  10.2  18.0  110.0   107  14.6  0.589  0.004  0.269  11.3  22.7  16.9   6.6   1.3   4.1  18.4  16.3  1.2  0.9  2.1  0.104  -1.5   0.8 -0.7   0.3  2014

In [99]:
# check results of the merge
df_2014.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 481 entries, 0 to 480
Data columns (total 51 columns):
Player    481 non-null object
Pos       481 non-null object
Age       481 non-null object
Tm        481 non-null object
G         481 non-null int64
GS        481 non-null int64
MP        481 non-null int64
FG        481 non-null float64
FGA       481 non-null float64
FG%       479 non-null float64
3P        481 non-null float64
3PA       481 non-null float64
3P%       414 non-null float64
2P        481 non-null float64
2PA       481 non-null float64
2P%       478 non-null float64
FT        481 non-null float64
FTA       481 non-null float64
FT%       461 non-null float64
ORB       481 non-null float64
DRB       481 non-null float64
TRB       481 non-null float64
AST       481 non-null float64
STL       481 non-null float64
BLK       481 non-null float64
TOV       481 non-null float64
PF        481 non-null float64
PTS       481 non-null float64
ORtg      480 non-null float64
DRtg      481 non-null int64
PER       481 non-null float64
TS%       479 non-null float64
3PAr      479 non-null float64
FTr       479 non-null float64
ORB%      481 non-null float64
DRB%      481 non-null float64
TRB%      481 non-null float64
AST%      481 non-null float64
STL%      481 non-null float64
BLK%      481 non-null float64
TOV%      480 non-null float64
USG%      481 non-null float64
OWS       481 non-null float64
DWS       481 non-null float64
WS        481 non-null float64
WS/48     481 non-null float64
OBPM      481 non-null float64
DBPM      481 non-null float64
BPM       481 non-null float64
VORP      481 non-null float64
Year      481 non-null int64
dtypes: float64(42), int64(5), object(4)
memory usage: 215.4+ KB

In [100]:
# export merged df to csv
df_2014.to_csv('data/df_2014.csv')

## Data Wrangling: 2013

In [101]:
# scrape per_poss and advanced stats for year 2013
per_poss2013 = basketball_reference_scrap(2013, 'per_poss')
advanced2013 = basketball_reference_scrap(2013, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2013.shape, 'Advanced: ', advanced2013.shape)

Shape of original DataFrames, Per_poss:  (596, 32) Advanced:  (596, 29)

In [102]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2013);

In [103]:
# check results of cleaning function for per possession stats
per_poss2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 31 columns):
Player    468 non-null object
Pos       468 non-null object
Age       468 non-null object
Tm        468 non-null object
G         468 non-null int64
GS        468 non-null int64
MP        468 non-null int64
FG        467 non-null float64
FGA       467 non-null float64
FG%       466 non-null float64
3P        467 non-null float64
3PA       467 non-null float64
3P%       404 non-null float64
2P        467 non-null float64
2PA       467 non-null float64
2P%       466 non-null float64
FT        467 non-null float64
FTA       467 non-null float64
FT%       455 non-null float64
ORB       467 non-null float64
DRB       467 non-null float64
TRB       467 non-null float64
AST       467 non-null float64
STL       467 non-null float64
BLK       467 non-null float64
TOV       467 non-null float64
PF        467 non-null float64
PTS       467 non-null float64
ORtg      467 non-null float64
DRtg      467 non-null float64
Year      468 non-null int64
dtypes: float64(23), int64(4), object(4)
memory usage: 113.4+ KB

In [104]:
# clean up advanced 2013 stats
clean_advanced(advanced2013);

In [105]:
# check results of cleaning function for advanced stats
advanced2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 27 columns):
Player    468 non-null object
Pos       468 non-null object
Age       468 non-null object
Tm        468 non-null object
G         468 non-null int64
MP        468 non-null int64
PER       467 non-null float64
TS%       466 non-null float64
3PAr      466 non-null float64
FTr       466 non-null float64
ORB%      467 non-null float64
DRB%      467 non-null float64
TRB%      467 non-null float64
AST%      467 non-null float64
STL%      467 non-null float64
BLK%      467 non-null float64
TOV%      466 non-null float64
USG%      467 non-null float64
OWS       468 non-null float64
DWS       468 non-null float64
WS        468 non-null float64
WS/48     467 non-null float64
OBPM      468 non-null float64
DBPM      468 non-null float64
BPM       468 non-null float64
VORP      468 non-null float64
Year      468 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 98.8+ KB

In [106]:
# check out new shape of each dataframe
print('Shape of new DataFrames, Per_poss: ', per_poss2013.shape, 'Advanced: ', advanced2013.shape)

Shape of new DataFrames, Per_poss:  (468, 31) Advanced:  (468, 27)

In [107]:
# merge the two dataframes
df_2013 = merge_df(per_poss2013, advanced2013)

df_2013.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP    FG   FGA    FG%   3P   3PA  3P%   2P   2PA    2P%   FT  FTA    FT%  ORB   DRB   TRB  AST  STL  BLK  TOV    PF   PTS   ORtg   DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0     Quincy Acy  PF  22  TOR  29   0   342   6.5  11.6  0.560  0.2   0.3  0.5  6.4  11.3  0.562  4.8  5.9  0.816  4.7   7.3  12.0  1.7  2.0  2.3  2.6   8.2  18.0  120.0  105.0  15.9  0.632  0.027  0.507  10.3  16.6  13.4   5.2   2.0   3.5  15.6  14.7  0.7  0.4  1.1  0.157  -0.6   1.3  0.7   0.2  2013
1    Jeff Adrien  PF  26  CHA  52   5   713   5.3  12.4  0.429  0.0   0.1  0.0  5.3  12.2  0.434  4.8  7.4  0.650  5.0   9.4  14.4  2.7  1.3  2.0  2.4   5.9  15.4  105.0  109.0  13.4  0.493  0.012  0.595  10.6  21.2  15.7   8.3   1.3   3.1  13.1  15.6  0.5  0.4  1.0  0.064  -3.0  -0.2 -3.3  -0.2  2013
2  Arron Afflalo  SF  27  ORL  64  64  2307   9.0  20.4  0.439  1.6   5.4  0.3  7.3  15.0  0.489  4.3  5.0  0.857  0.7   4.7   5.4  4.7  0.9  0.2  3.1   3.1  23.9  102.0  112.0  13.0  0.527  0.265  0.246   1.4  10.3   5.8  14.6   0.9   0.4  12.1  22.5  1.5  0.5  2.0  0.042  -0.3  -2.0 -2.3  -0.2  2013
3   Josh Akognon  PG  26  DAL   3   0     9  11.3  22.7  0.500  5.7  11.3  0.5  5.7  11.3  0.500  0.0  0.0    NaN  0.0   5.7   5.7  5.7  0.0  0.0  0.0  17.0  28.4  130.0  111.0  15.3  0.625  0.500  0.000   0.0  12.1   6.2  19.4   0.0   0.0   0.0  20.3  0.0  0.0  0.0  0.196   4.7  -4.9 -0.2   0.0  2013
4   Cole Aldrich   C  24  TOT  45   0   388   5.7  10.4  0.550  0.0   0.0  NaN  5.7  10.4  0.550  1.6  2.6  0.600  3.9  11.7  15.6  1.2  0.7  3.0  3.0   7.8  13.0  102.0  105.0  11.1  0.563  0.000  0.250   8.7  26.7  17.7   3.4   0.7   4.6  20.6  12.7  0.1  0.4  0.6  0.070  -4.8   0.7 -4.0  -0.2  2013

In [108]:
# check results of the merge
df_2013.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 468 entries, 0 to 467
Data columns (total 51 columns):
Player    468 non-null object
Pos       468 non-null object
Age       468 non-null object
Tm        468 non-null object
G         468 non-null int64
GS        468 non-null int64
MP        468 non-null int64
FG        467 non-null float64
FGA       467 non-null float64
FG%       466 non-null float64
3P        467 non-null float64
3PA       467 non-null float64
3P%       404 non-null float64
2P        467 non-null float64
2PA       467 non-null float64
2P%       466 non-null float64
FT        467 non-null float64
FTA       467 non-null float64
FT%       455 non-null float64
ORB       467 non-null float64
DRB       467 non-null float64
TRB       467 non-null float64
AST       467 non-null float64
STL       467 non-null float64
BLK       467 non-null float64
TOV       467 non-null float64
PF        467 non-null float64
PTS       467 non-null float64
ORtg      467 non-null float64
DRtg      467 non-null float64
PER       467 non-null float64
TS%       466 non-null float64
3PAr      466 non-null float64
FTr       466 non-null float64
ORB%      467 non-null float64
DRB%      467 non-null float64
TRB%      467 non-null float64
AST%      467 non-null float64
STL%      467 non-null float64
BLK%      467 non-null float64
TOV%      466 non-null float64
USG%      467 non-null float64
OWS       468 non-null float64
DWS       468 non-null float64
WS        468 non-null float64
WS/48     467 non-null float64
OBPM      468 non-null float64
DBPM      468 non-null float64
BPM       468 non-null float64
VORP      468 non-null float64
Year      468 non-null int64
dtypes: float64(43), int64(4), object(4)
memory usage: 210.1+ KB

In [109]:
# export merged df to csv
df_2013.to_csv('data/df_2013.csv')

## Data Wrangling: 2012

In [110]:
# scrape per_poss and advanced stats for year 2012
per_poss2012 = basketball_reference_scrap(2012, 'per_poss')
advanced2012 = basketball_reference_scrap(2012, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2012.shape, 'Advanced: ', advanced2012.shape)

Shape of original DataFrames, Per_poss:  (574, 32) Advanced:  (574, 29)

In [111]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2012);

In [112]:
# check results of cleaning function for per possession stats
per_poss2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478 entries, 0 to 477
Data columns (total 31 columns):
Player    478 non-null object
Pos       478 non-null object
Age       478 non-null object
Tm        478 non-null object
G         478 non-null int64
GS        478 non-null int64
MP        478 non-null int64
FG        478 non-null float64
FGA       478 non-null float64
FG%       478 non-null float64
3P        478 non-null float64
3PA       478 non-null float64
3P%       400 non-null float64
2P        478 non-null float64
2PA       478 non-null float64
2P%       478 non-null float64
FT        478 non-null float64
FTA       478 non-null float64
FT%       463 non-null float64
ORB       478 non-null float64
DRB       478 non-null float64
TRB       478 non-null float64
AST       478 non-null float64
STL       478 non-null float64
BLK       478 non-null float64
TOV       478 non-null float64
PF        478 non-null float64
PTS       478 non-null float64
ORtg      478 non-null int64
DRtg      478 non-null int64
Year      478 non-null int64
dtypes: float64(21), int64(6), object(4)
memory usage: 115.8+ KB

In [113]:
# clean up advanced stats
clean_advanced(advanced2012);

In [114]:
# check results of cleaning function for advanced stats
advanced2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478 entries, 0 to 477
Data columns (total 27 columns):
Player    478 non-null object
Pos       478 non-null object
Age       478 non-null object
Tm        478 non-null object
G         478 non-null int64
MP        478 non-null int64
PER       478 non-null float64
TS%       478 non-null float64
3PAr      478 non-null float64
FTr       478 non-null float64
ORB%      478 non-null float64
DRB%      478 non-null float64
TRB%      478 non-null float64
AST%      478 non-null float64
STL%      478 non-null float64
BLK%      478 non-null float64
TOV%      478 non-null float64
USG%      478 non-null float64
OWS       478 non-null float64
DWS       478 non-null float64
WS        478 non-null float64
WS/48     478 non-null float64
OBPM      478 non-null float64
DBPM      478 non-null float64
BPM       478 non-null float64
VORP      478 non-null float64
Year      478 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 100.9+ KB

In [115]:
# check out new shape of each dataframe
print('Shape of new DataFrames, Per_poss: ', per_poss2012.shape, 'Advanced: ', advanced2012.shape)

Shape of new DataFrames, Per_poss:  (478, 31) Advanced:  (478, 27)

In [116]:
# merge the two dataframes
df_2012 = merge_df(per_poss2012, advanced2012)

df_2012.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT   FTA    FT%  ORB   DRB   TRB  AST  STL  BLK  TOV    PF   PTS  ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM   BPM  VORP  Year
0    Jeff Adrien  PF  25  HOU   8   0    63  5.8  13.3  0.438  0.0   0.0    NaN  5.8  13.3  0.438  5.8  10.0  0.583  4.2  14.1  18.3  0.8  0.0  1.7  1.7  10.8  17.5   106   103  11.2  0.493  0.000  0.750   9.1  31.6  20.3   2.4   0.0   2.4   8.6  16.8  0.1  0.1  0.1  0.106  -5.4  -2.3  -7.7  -0.1  2012
1  Arron Afflalo  SG  26  DEN  62  62  2086  8.0  17.1  0.471  2.1   5.4  0.398  5.9  11.7  0.504  4.8   6.0  0.798  1.0   3.8   4.8  3.6  0.9  0.3  2.1   3.3  23.0   116   111  14.7  0.584  0.316  0.353   2.3   8.5   5.5  11.1   0.9   0.5   9.5  19.1  4.7  0.6  5.3  0.121   2.5  -1.6   0.8   1.5  2012
2   Blake Ahearn  PG  27  UTA   4   0    30  7.0  24.5  0.286  3.5  15.7  0.222  3.5   8.7  0.400  0.0   0.0    NaN  0.0   3.5   3.5  1.7  0.0  0.0  8.7   7.0  17.5    57   113  -7.3  0.357  0.643  0.000   0.0   7.7   3.8   5.2   0.0   0.0  26.3  28.4 -0.2  0.0 -0.2 -0.315 -10.3  -6.0 -16.3  -0.1  2012
3  Solomon Alabi   C  23  TOR  14   0   122  5.7  15.9  0.361  0.0   0.0    NaN  5.7  15.9  0.361  3.1   3.5  0.875  6.6  14.1  20.7  1.3  0.9  4.0  2.2   4.8  14.5    95    98  14.2  0.418  0.000  0.222  14.6  30.4  22.6   4.1   0.9   6.0  11.2  17.2  0.0  0.2  0.2  0.083  -5.6   1.5  -4.1  -0.1  2012
4   Cole Aldrich   C  23  OKC  26   0   173  6.6  12.5  0.524  0.0   0.0    NaN  6.6  12.5  0.524  3.9   4.2  0.929  3.9  10.4  14.3  0.9  2.4  4.8  2.7   6.6  17.0   113    96  17.7  0.592  0.000  0.333   9.2  21.6  15.8   2.7   2.4   6.7  15.7  14.9  0.3  0.4  0.6  0.176  -2.4   2.7   0.3   0.1  2012

In [117]:
# check results of the merge
df_2012.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 478 entries, 0 to 477
Data columns (total 51 columns):
Player    478 non-null object
Pos       478 non-null object
Age       478 non-null object
Tm        478 non-null object
G         478 non-null int64
GS        478 non-null int64
MP        478 non-null int64
FG        478 non-null float64
FGA       478 non-null float64
FG%       478 non-null float64
3P        478 non-null float64
3PA       478 non-null float64
3P%       400 non-null float64
2P        478 non-null float64
2PA       478 non-null float64
2P%       478 non-null float64
FT        478 non-null float64
FTA       478 non-null float64
FT%       463 non-null float64
ORB       478 non-null float64
DRB       478 non-null float64
TRB       478 non-null float64
AST       478 non-null float64
STL       478 non-null float64
BLK       478 non-null float64
TOV       478 non-null float64
PF        478 non-null float64
PTS       478 non-null float64
ORtg      478 non-null int64
DRtg      478 non-null int64
PER       478 non-null float64
TS%       478 non-null float64
3PAr      478 non-null float64
FTr       478 non-null float64
ORB%      478 non-null float64
DRB%      478 non-null float64
TRB%      478 non-null float64
AST%      478 non-null float64
STL%      478 non-null float64
BLK%      478 non-null float64
TOV%      478 non-null float64
USG%      478 non-null float64
OWS       478 non-null float64
DWS       478 non-null float64
WS        478 non-null float64
WS/48     478 non-null float64
OBPM      478 non-null float64
DBPM      478 non-null float64
BPM       478 non-null float64
VORP      478 non-null float64
Year      478 non-null int64
dtypes: float64(41), int64(6), object(4)
memory usage: 214.2+ KB

In [118]:
# export merged df to csv
df_2012.to_csv('data/df_2012.csv')

## Data Wrangling: 2011

In [119]:
# scrape per_poss and advanced stats for year 2011
per_poss2011 = basketball_reference_scrap(2011, 'per_poss')
advanced2011 = basketball_reference_scrap(2011, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2011.shape, 'Advanced: ', advanced2011.shape)

Shape of original DataFrames, Per_poss:  (647, 32) Advanced:  (647, 29)

In [120]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2011);

In [121]:
# check results of cleaning function for per possession stats
per_poss2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 31 columns):
Player    452 non-null object
Pos       452 non-null object
Age       452 non-null object
Tm        452 non-null object
G         452 non-null int64
GS        452 non-null int64
MP        452 non-null int64
FG        452 non-null float64
FGA       452 non-null float64
FG%       449 non-null float64
3P        452 non-null float64
3PA       452 non-null float64
3P%       382 non-null float64
2P        452 non-null float64
2PA       452 non-null float64
2P%       448 non-null float64
FT        452 non-null float64
FTA       452 non-null float64
FT%       437 non-null float64
ORB       452 non-null float64
DRB       452 non-null float64
TRB       452 non-null float64
AST       452 non-null float64
STL       452 non-null float64
BLK       452 non-null float64
TOV       452 non-null float64
PF        452 non-null float64
PTS       452 non-null float64
ORtg      449 non-null float64
DRtg      452 non-null int64
Year      452 non-null int64
dtypes: float64(22), int64(5), object(4)
memory usage: 109.5+ KB

In [122]:
# clean up advanced stats
clean_advanced(advanced2011);

In [123]:
# check results of cleaning function for advanced stats
advanced2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 27 columns):
Player    452 non-null object
Pos       452 non-null object
Age       452 non-null object
Tm        452 non-null object
G         452 non-null int64
MP        452 non-null int64
PER       452 non-null float64
TS%       449 non-null float64
3PAr      449 non-null float64
FTr       449 non-null float64
ORB%      452 non-null float64
DRB%      452 non-null float64
TRB%      452 non-null float64
AST%      452 non-null float64
STL%      452 non-null float64
BLK%      452 non-null float64
TOV%      449 non-null float64
USG%      452 non-null float64
OWS       452 non-null float64
DWS       452 non-null float64
WS        452 non-null float64
WS/48     452 non-null float64
OBPM      452 non-null float64
DBPM      452 non-null float64
BPM       452 non-null float64
VORP      452 non-null float64
Year      452 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 95.4+ KB

In [124]:
# check out new shape of each dataframe
print('Shape of new DataFrames, Per_poss: ', per_poss2011.shape, 'Advanced: ', advanced2011.shape)

Shape of new DataFrames, Per_poss:  (452, 31) Advanced:  (452, 27)

In [125]:
# merge the two dataframes
df_2011 = merge_df(per_poss2011, advanced2011)

df_2011.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP    FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV    PF   PTS   ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0    Jeff Adrien  PF  24  GSW  23   0   196   5.9  13.9  0.426  0.0  0.0    NaN  5.9  13.9  0.426  2.8  4.9  0.579  5.9  9.0  15.0  2.6  1.0  1.3  2.3   7.2  14.7  102.0   110  11.3  0.457  0.000  0.352  13.0  20.7  16.8   7.3   1.0   1.9  12.6  16.1  0.1  0.1  0.2  0.051  -3.9  -1.2 -5.1  -0.2  2011
1  Arron Afflalo  SG  25  DEN  69  69  2324   6.7  13.5  0.498  2.3  5.4  0.423  4.5   8.2  0.546  3.0  3.5  0.847  1.0  4.5   5.4  3.6  0.7  0.7  1.5   3.3  18.7  123.0   111  13.6  0.620  0.396  0.260   2.3   9.9   6.2  10.9   0.7   1.0   9.2  14.8  4.8  1.4  6.2  0.128   2.4  -0.2  2.1   2.4  2011
2   Maurice Ager  SG  26  MIN   4   0    29  10.3  18.9  0.545  5.1  6.9  0.750  5.1  12.0  0.429  0.0  0.0    NaN  0.0  3.4   3.4  1.7  1.7  0.0  6.9   6.9  25.7   94.0   114  10.1  0.682  0.364  0.000   0.0   7.9   3.8   6.0   1.7   0.0  26.7  22.0  0.0  0.0  0.0 -0.015  -2.7  -3.6 -6.3   0.0  2011
3  Alexis Ajinca   C  22  TOT  34   2   340   9.0  20.3  0.444  1.8  5.2  0.353  7.2  15.1  0.475  2.0  2.7  0.722  2.6  9.3  11.9  1.5  1.7  2.9  2.7  11.1  21.8   98.0   107  12.2  0.507  0.256  0.135   5.9  21.5  13.6   4.8   1.7   4.2  11.3  21.1  0.0  0.4  0.4  0.052  -3.1  -0.3 -3.4  -0.1  2011
4  Solomon Alabi   C  22  TOR  12   0    59   2.6  13.1  0.200  0.0  0.0    NaN  2.6  13.1  0.200  0.0  1.8  0.000  6.1  6.1  12.3  1.8  1.8  1.8  2.6   4.4   5.3   61.0   112   2.0  0.189  0.000  0.133  13.7  14.4  14.1   4.6   1.8   2.6  15.9  14.3 -0.2  0.0 -0.2 -0.142  -8.2   0.0 -8.2  -0.1  2011

In [126]:
# check results of the merge
df_2011.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 452 entries, 0 to 451
Data columns (total 51 columns):
Player    452 non-null object
Pos       452 non-null object
Age       452 non-null object
Tm        452 non-null object
G         452 non-null int64
GS        452 non-null int64
MP        452 non-null int64
FG        452 non-null float64
FGA       452 non-null float64
FG%       449 non-null float64
3P        452 non-null float64
3PA       452 non-null float64
3P%       382 non-null float64
2P        452 non-null float64
2PA       452 non-null float64
2P%       448 non-null float64
FT        452 non-null float64
FTA       452 non-null float64
FT%       437 non-null float64
ORB       452 non-null float64
DRB       452 non-null float64
TRB       452 non-null float64
AST       452 non-null float64
STL       452 non-null float64
BLK       452 non-null float64
TOV       452 non-null float64
PF        452 non-null float64
PTS       452 non-null float64
ORtg      449 non-null float64
DRtg      452 non-null int64
PER       452 non-null float64
TS%       449 non-null float64
3PAr      449 non-null float64
FTr       449 non-null float64
ORB%      452 non-null float64
DRB%      452 non-null float64
TRB%      452 non-null float64
AST%      452 non-null float64
STL%      452 non-null float64
BLK%      452 non-null float64
TOV%      449 non-null float64
USG%      452 non-null float64
OWS       452 non-null float64
DWS       452 non-null float64
WS        452 non-null float64
WS/48     452 non-null float64
OBPM      452 non-null float64
DBPM      452 non-null float64
BPM       452 non-null float64
VORP      452 non-null float64
Year      452 non-null int64
dtypes: float64(42), int64(5), object(4)
memory usage: 203.6+ KB

In [127]:
# export merged df to csv
df_2011.to_csv('data/df_2011.csv')

## Data Wrangling: 2010

In [128]:
# scrape per_poss and advanced stats for year 2010
per_poss2010 = basketball_reference_scrap(2010, 'per_poss')
advanced2010 = basketball_reference_scrap(2010, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2010.shape, 'Advanced: ', advanced2010.shape)

Shape of original DataFrames, Per_poss:  (600, 32) Advanced:  (600, 29)

In [129]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2010);

In [130]:
# check results of cleaning function for per possession stats
per_poss2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 31 columns):
Player    442 non-null object
Pos       442 non-null object
Age       442 non-null object
Tm        442 non-null object
G         442 non-null int64
GS        442 non-null int64
MP        442 non-null int64
FG        441 non-null float64
FGA       441 non-null float64
FG%       440 non-null float64
3P        441 non-null float64
3PA       441 non-null float64
3P%       379 non-null float64
2P        441 non-null float64
2PA       441 non-null float64
2P%       440 non-null float64
FT        441 non-null float64
FTA       441 non-null float64
FT%       433 non-null float64
ORB       441 non-null float64
DRB       441 non-null float64
TRB       441 non-null float64
AST       441 non-null float64
STL       441 non-null float64
BLK       441 non-null float64
TOV       441 non-null float64
PF        441 non-null float64
PTS       441 non-null float64
ORtg      440 non-null float64
DRtg      441 non-null float64
Year      442 non-null int64
dtypes: float64(23), int64(4), object(4)
memory usage: 107.1+ KB

In [131]:
# clean up advanced stats
clean_advanced(advanced2010);

In [132]:
# check results of cleaning function for advanced stats
advanced2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 27 columns):
Player    442 non-null object
Pos       442 non-null object
Age       442 non-null object
Tm        442 non-null object
G         442 non-null int64
MP        442 non-null int64
PER       441 non-null float64
TS%       440 non-null float64
3PAr      440 non-null float64
FTr       440 non-null float64
ORB%      441 non-null float64
DRB%      441 non-null float64
TRB%      441 non-null float64
AST%      441 non-null float64
STL%      441 non-null float64
BLK%      441 non-null float64
TOV%      440 non-null float64
USG%      441 non-null float64
OWS       442 non-null float64
DWS       442 non-null float64
WS        442 non-null float64
WS/48     441 non-null float64
OBPM      442 non-null float64
DBPM      442 non-null float64
BPM       442 non-null float64
VORP      442 non-null float64
Year      442 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 93.3+ KB

In [133]:
# check out new shape of each dataframe
print('Shape of new DataFrames, Per_poss: ', per_poss2010.shape, 'Advanced: ', advanced2010.shape)

Shape of new DataFrames, Per_poss:  (442, 31) Advanced:  (442, 27)

In [134]:
# merge the two dataframes
df_2010 = merge_df(per_poss2010, advanced2010)

df_2010.head(5)

Do all three DataFrames have the same number of rows?  True

              Player Pos Age   Tm   G  GS    MP    FG   FGA    FG%   3P  3PA    3P%    2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV    PF   PTS   ORtg   DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM   BPM  VORP  Year
0      Arron Afflalo  SG  24  DEN  82  75  2221   6.2  13.3  0.465  2.5  5.7  0.434   3.7   7.7  0.488  1.6  2.2  0.735  1.3  4.4   5.7  3.1  1.0  0.7  1.7   5.1  16.5  114.0  111.0  10.9  0.576  0.426  0.168   3.1   9.9   6.5   9.3   1.0   1.0  10.5  14.0  2.8  1.4  4.3  0.092   0.8  -0.5   0.3   1.3  2010
1      Alexis Ajinca   C  21  CHA   6   0    30   8.9  17.7  0.500  0.0  0.0    NaN   8.9  17.7  0.500  0.0  1.8  0.000  1.8  5.3   7.1  0.0  1.8  1.8  3.5   8.9  17.7   81.0  103.0   6.3  0.479  0.000  0.100   4.1  11.8   8.0   0.0   1.8   2.7  16.1  19.3 -0.1  0.0  0.0 -0.013  -8.5  -2.0 -10.4  -0.1  2010
2  LaMarcus Aldridge  PF  24  POR  78  78  2922  10.8  21.9  0.495  0.1  0.3  0.313  10.7  21.6  0.498  4.3  5.7  0.757  3.6  8.1  11.7  3.0  1.3  0.9  1.9   4.3  26.1  113.0  107.0  18.2  0.535  0.014  0.260   8.1  18.6  13.3   9.9   1.3   1.3   7.4  22.9  5.5  3.3  8.8  0.145   0.9   0.6   1.6   2.6  2010
3      Joe Alexander  SF  23  CHI   8   0    29   1.8  10.7  0.167  0.0  1.8  0.000   1.8   8.9  0.200  3.6  5.3  0.667  3.6  5.3   8.9  3.6  1.8  1.8  0.0  16.0   7.1   88.0  104.0   2.8  0.273  0.167  0.500   7.8  11.3   9.6   9.3   1.8   2.6   0.0  11.3  0.0  0.0  0.0  0.030  -5.2   1.5  -3.7   0.0  2010
4        Malik Allen  PF  31  DEN  51   3   456   5.1  12.9  0.397  0.1  0.7  0.167   5.0  12.2  0.409  1.3  1.4  0.923  4.0  5.1   9.1  1.8  1.2  0.6  2.4   7.6  11.7   93.0  110.0   5.9  0.431  0.052  0.112   9.2  11.5  10.4   5.1   1.2   0.8  15.3  14.0 -0.3  0.3  0.1  0.009  -4.2  -0.8  -5.0  -0.3  2010

In [135]:
# check results of the merge
df_2010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 442 entries, 0 to 441
Data columns (total 51 columns):
Player    442 non-null object
Pos       442 non-null object
Age       442 non-null object
Tm        442 non-null object
G         442 non-null int64
GS        442 non-null int64
MP        442 non-null int64
FG        441 non-null float64
FGA       441 non-null float64
FG%       440 non-null float64
3P        441 non-null float64
3PA       441 non-null float64
3P%       379 non-null float64
2P        441 non-null float64
2PA       441 non-null float64
2P%       440 non-null float64
FT        441 non-null float64
FTA       441 non-null float64
FT%       433 non-null float64
ORB       441 non-null float64
DRB       441 non-null float64
TRB       441 non-null float64
AST       441 non-null float64
STL       441 non-null float64
BLK       441 non-null float64
TOV       441 non-null float64
PF        441 non-null float64
PTS       441 non-null float64
ORtg      440 non-null float64
DRtg      441 non-null float64
PER       441 non-null float64
TS%       440 non-null float64
3PAr      440 non-null float64
FTr       440 non-null float64
ORB%      441 non-null float64
DRB%      441 non-null float64
TRB%      441 non-null float64
AST%      441 non-null float64
STL%      441 non-null float64
BLK%      441 non-null float64
TOV%      440 non-null float64
USG%      441 non-null float64
OWS       442 non-null float64
DWS       442 non-null float64
WS        442 non-null float64
WS/48     441 non-null float64
OBPM      442 non-null float64
DBPM      442 non-null float64
BPM       442 non-null float64
VORP      442 non-null float64
Year      442 non-null int64
dtypes: float64(43), int64(4), object(4)
memory usage: 199.6+ KB

In [136]:
# export merged df to csv
df_2010.to_csv('data/df_2010.csv')

## Data Wrangling: 2009

In [137]:
# scrape per_poss and advanced stats for year 2009
per_poss2009 = basketball_reference_scrap(2009, 'per_poss')
advanced2009 = basketball_reference_scrap(2009, 'advanced')

print('Shape of original DataFrames, Per_poss: ', per_poss2009.shape, 'Advanced: ', advanced2009.shape)

Shape of original DataFrames, Per_poss:  (604, 32) Advanced:  (604, 29)

In [138]:
# clean per possession data with clean_per_poss function
clean_per_poss(per_poss2009);

In [139]:
# check results of cleaning function for per possession stats
per_poss2009.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 31 columns):
Player    444 non-null object
Pos       444 non-null object
Age       444 non-null object
Tm        444 non-null object
G         444 non-null int64
GS        444 non-null int64
MP        444 non-null int64
FG        444 non-null float64
FGA       444 non-null float64
FG%       444 non-null float64
3P        444 non-null float64
3PA       444 non-null float64
3P%       372 non-null float64
2P        444 non-null float64
2PA       444 non-null float64
2P%       443 non-null float64
FT        444 non-null float64
FTA       444 non-null float64
FT%       430 non-null float64
ORB       444 non-null float64
DRB       444 non-null float64
TRB       444 non-null float64
AST       444 non-null float64
STL       444 non-null float64
BLK       444 non-null float64
TOV       444 non-null float64
PF        444 non-null float64
PTS       444 non-null float64
ORtg      444 non-null int64
DRtg      444 non-null int64
Year      444 non-null int64
dtypes: float64(21), int64(6), object(4)
memory usage: 107.6+ KB

In [140]:
# clean up advanced stats
clean_advanced(advanced2009);

In [141]:
# check results of cleaning function for advanced stats
advanced2009.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 27 columns):
Player    444 non-null object
Pos       444 non-null object
Age       444 non-null object
Tm        444 non-null object
G         444 non-null int64
MP        444 non-null int64
PER       444 non-null float64
TS%       444 non-null float64
3PAr      444 non-null float64
FTr       444 non-null float64
ORB%      444 non-null float64
DRB%      444 non-null float64
TRB%      444 non-null float64
AST%      444 non-null float64
STL%      444 non-null float64
BLK%      444 non-null float64
TOV%      444 non-null float64
USG%      444 non-null float64
OWS       444 non-null float64
DWS       444 non-null float64
WS        444 non-null float64
WS/48     444 non-null float64
OBPM      444 non-null float64
DBPM      444 non-null float64
BPM       444 non-null float64
VORP      444 non-null float64
Year      444 non-null int64
dtypes: float64(20), int64(3), object(4)
memory usage: 93.7+ KB

In [142]:
# check out new shape of each dataframe
print('Shape of new DataFrames, Per_poss: ', per_poss2009.shape, 'Advanced: ', advanced2009.shape)

Shape of new DataFrames, Per_poss:  (444, 31) Advanced:  (444, 27)

In [143]:
# merge the two dataframes
df_2009 = merge_df(per_poss2009, advanced2009)

df_2009.head(5)

Do all three DataFrames have the same number of rows?  True

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  ORtg  DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM   BPM  VORP  Year
0     Alex Acker  SG  26  TOT  25   0   199  7.9  20.0  0.395  1.8   5.3  0.350  6.1  14.8  0.411  1.3  2.6  0.500  2.1  4.2  6.3  3.2  1.3  1.1  1.8  2.4  19.0    94   114  10.4  0.448  0.263  0.132   4.5   9.6   7.0  10.2   1.3   1.5   8.0  20.1 -0.1  0.1  0.0 -0.011  -3.6  -2.4  -6.0  -0.2  2009
1   Hassan Adams  SG  24  TOR  12   0    52  4.0  13.0  0.308  0.0   0.0    NaN  4.0  13.0  0.308  3.0  6.0  0.500  1.0  6.0  7.0  1.0  1.0  1.0  4.0  4.0  11.0    63   111   0.4  0.352  0.000  0.462   2.3  13.4   7.9   2.8   1.0   1.5  20.4  17.4 -0.2  0.0 -0.2 -0.144 -10.6  -1.3 -12.0  -0.1  2009
2  Arron Afflalo  SG  23  DET  74   8  1234  5.9  13.5  0.437  1.9   4.8  0.402  3.9   8.7  0.456  2.6  3.2  0.817  1.3  4.7  6.0  2.0  1.3  0.6  1.9  6.5  16.3   107   110   8.9  0.548  0.357  0.237   2.8  10.1   6.4   5.5   1.3   0.8  11.5  14.5  0.8  1.0  1.8  0.069  -1.7  -0.7  -2.4  -0.1  2009
3   Maurice Ager  SG  24  NJN  20   0    97  8.3  23.7  0.349  0.0   3.3  0.000  8.3  20.4  0.405  2.2  4.4  0.500  1.7  3.9  5.5  1.7  0.6  1.1  2.2  9.4  18.7    77   115   2.2  0.365  0.140  0.186   3.6   8.7   6.1   5.3   0.6   1.7   7.9  24.4 -0.3  0.0 -0.3 -0.133  -8.5  -4.3 -12.8  -0.3  2009
4   Blake Ahearn  PG  24  SAS   3   0    19  5.7  17.1  0.333  5.7  11.4  0.500  0.0   5.7  0.000  5.7  5.7  1.000  0.0  2.9  2.9  5.7  2.9  0.0  2.9  8.6  22.9   113   104  12.9  0.581  0.667  0.333   0.0   6.2   3.1  16.0   2.9   0.0  12.7  20.1  0.0  0.0  0.1  0.149   0.6  -1.8  -1.1   0.0  2009

In [144]:
# check results of the merge
df_2009.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 444 entries, 0 to 443
Data columns (total 51 columns):
Player    444 non-null object
Pos       444 non-null object
Age       444 non-null object
Tm        444 non-null object
G         444 non-null int64
GS        444 non-null int64
MP        444 non-null int64
FG        444 non-null float64
FGA       444 non-null float64
FG%       444 non-null float64
3P        444 non-null float64
3PA       444 non-null float64
3P%       372 non-null float64
2P        444 non-null float64
2PA       444 non-null float64
2P%       443 non-null float64
FT        444 non-null float64
FTA       444 non-null float64
FT%       430 non-null float64
ORB       444 non-null float64
DRB       444 non-null float64
TRB       444 non-null float64
AST       444 non-null float64
STL       444 non-null float64
BLK       444 non-null float64
TOV       444 non-null float64
PF        444 non-null float64
PTS       444 non-null float64
ORtg      444 non-null int64
DRtg      444 non-null int64
PER       444 non-null float64
TS%       444 non-null float64
3PAr      444 non-null float64
FTr       444 non-null float64
ORB%      444 non-null float64
DRB%      444 non-null float64
TRB%      444 non-null float64
AST%      444 non-null float64
STL%      444 non-null float64
BLK%      444 non-null float64
TOV%      444 non-null float64
USG%      444 non-null float64
OWS       444 non-null float64
DWS       444 non-null float64
WS        444 non-null float64
WS/48     444 non-null float64
OBPM      444 non-null float64
DBPM      444 non-null float64
BPM       444 non-null float64
VORP      444 non-null float64
Year      444 non-null int64
dtypes: float64(41), int64(6), object(4)
memory usage: 200.4+ KB

In [145]:
# export merged df to csv
df_2009.to_csv('data/df_2009.csv')

# Combine all DF's Together

In [146]:
list_dfs = [df_2018, df_2017, df_2016, df_2015, df_2014, df_2013,
           df_2012, df_2011, df_2010, df_2009]

In [148]:
pd.concat(list_dfs)

(4759, 51)

In [149]:
df_all = pd.concat(list_dfs)

In [150]:
df_all.head(5)

          Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS   ORtg   DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  Year
0   Alex Abrines  SG  24  OKC  75   8  1134  5.0  12.7  0.395  3.7   9.7  0.380  1.4   3.1  0.443  1.7  2.0  0.848  1.1  3.9   5.0  1.2  1.7  0.4  1.1  5.4  15.4  116.0  110.0   9.0  0.567  0.759  0.158   2.5   8.9   5.6   3.4   1.7   0.6   7.4  12.7  1.3  1.0  2.2  0.094  -0.5  -1.7 -2.2  -0.1  2018
1     Quincy Acy  PF  27  BRK  70   8  1359  4.6  13.0  0.356  3.6  10.4  0.349  1.0   2.6  0.384  1.8  2.1  0.817  1.4  7.8   9.2  2.0  1.2  1.0  2.1  5.3  14.7   99.0  110.0   8.2  0.525  0.800  0.164   3.1  17.1  10.0   6.0   1.2   1.6  13.3  14.4 -0.1  1.1  1.0  0.036  -2.0  -0.2 -2.2  -0.1  2018
2   Steven Adams   C  24  OKC  76  76  2487  8.9  14.2  0.629  0.0   0.0  0.000  8.9  14.2  0.631  3.2  5.7  0.559  7.7  6.0  13.7  1.8  1.8  1.6  2.6  4.3  21.1  125.0  107.0  20.6  0.630  0.003  0.402  16.6  13.9  15.3   5.5   1.8   2.8  13.3  16.7  6.7  3.0  9.7  0.187   2.2   1.1  3.3   3.3  2018
3    Bam Adebayo   C  20  MIA  69  19  1368  6.4  12.5  0.512  0.0   0.3  0.000  6.4  12.2  0.523  4.7  6.6  0.721  4.3  9.7  14.0  3.7  1.2  1.5  2.4  5.1  17.5  116.0  105.0  15.7  0.570  0.021  0.526   9.7  21.6  15.6  11.0   1.2   2.5  13.6  15.9  2.3  1.9  4.2  0.148  -1.6   1.8  0.2   0.8  2018
4  Arron Afflalo  SG  32  ORL  53   3   682  4.7  11.6  0.401  1.9   5.0  0.386  2.7   6.6  0.413  1.6  1.9  0.846  0.3  4.5   4.7  2.2  0.3  0.6  1.5  4.0  12.8   98.0  115.0   5.8  0.516  0.432  0.160   0.6  10.1   5.3   6.2   0.3   1.1  10.8  12.5 -0.1  0.2  0.1  0.009  -4.1  -1.8 -5.8  -0.7  2018

In [151]:
df_all.tail(5)

              Player Pos Age   Tm   G  GS    MP   FG   FGA    FG%   3P   3PA    3P%   2P   2PA    2P%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV    PF   PTS   ORtg   DRtg   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM   BPM  VORP  Year
439    Julian Wright  SF  21  NOH  54  19   772  7.7  16.6  0.466  0.1   1.5  0.095  7.6  15.1  0.502  1.2  2.1  0.567  3.3  7.5  10.8  3.0  2.5  1.3  3.0   3.5  16.8   95.0  104.0  12.6  0.479  0.090  0.128   7.2  16.6  11.9   9.4   2.5   2.1  14.8  18.1 -0.4  1.2  0.8  0.048  -3.7   1.6  -2.1   0.0  2009
440  Lorenzen Wright   C  33  CLE  17   2   125  4.3  11.7  0.370  0.0   0.0    NaN  4.3  11.7  0.370  1.3  3.5  0.375  3.0  7.8  10.8  1.3  1.7  2.2  3.9   7.4  10.0   73.0  101.0   4.0  0.377  0.000  0.296   6.9  16.5  11.9   3.5   1.7   3.2  22.8  14.9 -0.3  0.2 -0.1 -0.022  -8.4   2.0  -6.4  -0.1  2009
441       Nick Young  SG  23  WAS  82   5  1837  9.6  21.7  0.444  1.6   4.7  0.341  8.0  17.0  0.473  4.7  5.5  0.850  0.9  3.4   4.3  2.7  1.1  0.6  2.6   4.0  25.6  105.0  117.0  13.1  0.530  0.217  0.255   1.9   7.8   4.8   9.0   1.1   0.9   9.9  23.1  1.2 -0.1  1.2  0.030  -1.1  -3.8  -4.9  -1.3  2009
442   Thaddeus Young  PF  20  PHI  75  71  2580  9.8  19.9  0.495  1.2   3.4  0.341  8.7  16.5  0.526  2.9  3.9  0.735  2.9  4.9   7.8  1.8  2.1  0.5  2.4   3.4  23.7  110.0  109.0  15.3  0.549  0.171  0.197   6.4  11.1   8.8   5.8   2.1   0.7  10.2  20.5  3.0  2.5  5.5  0.102   0.8  -0.2   0.5   1.7  2009
443          Sun Yue  SG  23  LAL  10   0    28  5.5  20.0  0.273  0.0  10.9  0.000  5.5   9.1  0.600  0.0  0.0    NaN  0.0  0.0   0.0  3.6  1.8  1.8  5.5  18.2  10.9   53.0  108.0  -8.6  0.273  0.545  0.000   0.0   0.0   0.0   9.8   1.8   2.8  21.4  22.0 -0.2  0.0 -0.1 -0.226 -11.4  -3.7 -15.2  -0.1  2009

In [154]:
df_all.reset_index(drop=True, inplace = True);

In [155]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4759 entries, 0 to 4758
Data columns (total 51 columns):
Player    4759 non-null object
Pos       4759 non-null object
Age       4759 non-null object
Tm        4759 non-null object
G         4759 non-null int64
GS        4759 non-null int64
MP        4759 non-null int64
FG        4757 non-null float64
FGA       4757 non-null float64
FG%       4743 non-null float64
3P        4757 non-null float64
3PA       4757 non-null float64
3P%       4150 non-null float64
2P        4757 non-null float64
2PA       4757 non-null float64
2P%       4725 non-null float64
FT        4757 non-null float64
FTA       4757 non-null float64
FT%       4588 non-null float64
ORB       4757 non-null float64
DRB       4757 non-null float64
TRB       4757 non-null float64
AST       4757 non-null float64
STL       4757 non-null float64
BLK       4757 non-null float64
TOV       4757 non-null float64
PF        4757 non-null float64
PTS       4757 non-null float64
ORtg      4748 non-null float64
DRtg      4757 non-null float64
PER       4757 non-null float64
TS%       4743 non-null float64
3PAr      4743 non-null float64
FTr       4743 non-null float64
ORB%      4757 non-null float64
DRB%      4757 non-null float64
TRB%      4757 non-null float64
AST%      4757 non-null float64
STL%      4757 non-null float64
BLK%      4757 non-null float64
TOV%      4745 non-null float64
USG%      4757 non-null float64
OWS       4759 non-null float64
DWS       4759 non-null float64
WS        4759 non-null float64
WS/48     4757 non-null float64
OBPM      4759 non-null float64
DBPM      4759 non-null float64
BPM       4759 non-null float64
VORP      4759 non-null float64
Year      4759 non-null int64
dtypes: float64(43), int64(4), object(4)
memory usage: 1.9+ MB

In [160]:
# percentage of the column with a missing value
df_all.isnull().sum() / len(df_all) * 100

Player     0.000000
Pos        0.000000
Age        0.000000
Tm         0.000000
G          0.000000
GS         0.000000
MP         0.000000
FG         0.042026
FGA        0.042026
FG%        0.336205
3P         0.042026
3PA        0.042026
3P%       12.796806
2P         0.042026
2PA        0.042026
2P%        0.714436
FT         0.042026
FTA        0.042026
FT%        3.593192
ORB        0.042026
DRB        0.042026
TRB        0.042026
AST        0.042026
STL        0.042026
BLK        0.042026
TOV        0.042026
PF         0.042026
PTS        0.042026
ORtg       0.231141
DRtg       0.042026
PER        0.042026
TS%        0.336205
3PAr       0.336205
FTr        0.336205
ORB%       0.042026
DRB%       0.042026
TRB%       0.042026
AST%       0.042026
STL%       0.042026
BLK%       0.042026
TOV%       0.294179
USG%       0.042026
OWS        0.000000
DWS        0.000000
WS         0.000000
WS/48      0.042026
OBPM       0.000000
DBPM       0.000000
BPM        0.000000
VORP       0.000000
Year       0.000000
dtype: float64

In [162]:
three_point_nulls = df_all[df_all['3P%'].isnull()]

In [163]:
three_point_nulls.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'ORtg', 'DRtg', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP', 'Year'], dtype='object')

In [169]:
# statistical overview of '3PA' for observations with , i.e. number of 3-pointers attempted
three_point_nulls['3PA'].describe()

count    607.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: 3PA, dtype: float64

As we can see, _all_ of the players that had a null value for `3P%` also didn't attempt a _single_ 3-point shot! I now feel comfortable replacing `0` for all the `NaN` values in this column.

In [176]:
df_all['3P%'].fillna(value = 0, inplace = True);

In [178]:
# check to see the null values in 3P% column
df_all['3P%'].isnull().sum()

0

It looks like `FT%` also had quite a few null values (approx. 3.6% of column). Let's check this out and see what's going on.

In [180]:
# dataframe with observations that contain a null value for FT%
free_throw_nulls = df_all[df_all['FT%'].isnull()]

In [181]:
# similar to 3P%, let's check out how many free throw attempts these players made
free_throw_nulls['FTA'].describe()

count    169.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: FTA, dtype: float64

Similar to `3PA`, the null observations for free throws also did not attempt any free throws. So we'll go ahead and replace the null values in the `FTA` column with 0.

In [182]:
df_all['FT%'].fillna(value = 0, inplace = True);

In [183]:
# check to see the null values in FT% column
df_all['FT%'].isnull().sum()

0

In [184]:
# missing values in each column
df_all.isnull().sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         2
FGA        2
FG%       16
3P         2
3PA        2
3P%        0
2P         2
2PA        2
2P%       34
FT         2
FTA        2
FT%        0
ORB        2
DRB        2
TRB        2
AST        2
STL        2
BLK        2
TOV        2
PF         2
PTS        2
ORtg      11
DRtg       2
PER        2
TS%       16
3PAr      16
FTr       16
ORB%       2
DRB%       2
TRB%       2
AST%       2
STL%       2
BLK%       2
TOV%      14
USG%       2
OWS        0
DWS        0
WS         0
WS/48      2
OBPM       0
DBPM       0
BPM        0
VORP       0
Year       0
dtype: int64

In [189]:
# see observations where '2P%' is null
df_all[df_all['2P%'].isnull()]

                    Player Pos Age   Tm   G  GS   MP    FG   FGA    FG%    3P   3PA    3P%   2P  2PA  2P%    FT   FTA  FT%   ORB   DRB   TRB   AST  STL  BLK   TOV    PF    PTS   ORtg   DRtg    PER    TS%  3PAr    FTr  ORB%   DRB%  TRB%  AST%  STL%  BLK%   TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM   BPM  VORP  Year
59           Chris Boucher  PF  25  GSW   1   0    1   0.0  48.2  0.000   0.0  48.2  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0  48.2  48.2   0.0  0.0  0.0   0.0   0.0    0.0    0.0   88.0  -28.5  0.000   1.0  0.000   0.0  100.0  55.9   0.0   0.0   0.0    0.0  43.9  0.0  0.0  0.0 -0.899 -38.9 -20.1 -59.0   0.0  2018
67           Anthony Brown  SF  25  MIN   1   0    4  12.5  12.5  1.000  12.5  12.5  1.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0  12.5  0.0  0.0   0.0   0.0   37.5  279.0  120.0   41.9  1.500   1.0  0.000   0.0    0.0   0.0  41.7   0.0   0.0    0.0  11.1  0.0  0.0  0.0  0.571  17.1 -15.0   2.1   0.0  2018
73        Nicolas Brussino  SF  24  ATL   4   0   10   0.0   9.8  0.000   0.0   9.8  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0  14.7  14.7   0.0  0.0  0.0   0.0   0.0    0.0    0.0  111.0   -4.6  0.000   1.0  0.000   0.0   33.5  16.7   0.0   0.0   0.0    0.0   8.7  0.0  0.0  0.0 -0.180 -13.8  -4.7 -18.5   0.0  2018
143           Jarell Eddie  SF  26  TOT   3   0    9   0.0  11.0  0.000   0.0  11.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   5.5   5.5   0.0  5.5  0.0   0.0   0.0    0.0    0.0  100.0   -1.9  0.000   1.0  0.000   0.0   12.0   6.1   0.0   5.6   0.0    0.0   9.8  0.0  0.0  0.0 -0.142 -10.0   1.6  -8.4   0.0  2018
207           Reggie Hearn  SG  26  DET   3   0    7   7.1  14.3  0.500   7.1  14.3  0.500  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0   0.0   21.4  143.0  116.0   13.1  0.750   1.0  0.000   0.0    0.0   0.0   0.0   0.0   0.0    0.0  12.7  0.0  0.0  0.0  0.132   2.8  -5.1  -2.3   0.0  2018
306            Tyler Lydon  PF  21  DEN   1   0    2   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0   0.0    0.0    NaN  120.0    0.0    NaN   NaN    NaN   0.0    0.0   0.0   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0 -0.014  -5.7  -0.8  -6.5   0.0  2018
319   James Michael McAdoo  PF  25  PHI   3   0   18   5.3  18.7  0.286   5.3  18.7  0.286  0.0  0.0  NaN   5.3   5.3  1.0   0.0   5.3   5.3   0.0  0.0  2.7   2.7   2.7   21.4   94.0  108.0    7.4  0.508   1.0  0.286   0.0   11.5   6.0   0.0   0.0   4.6   11.3  21.0  0.0  0.0  0.0  0.023  -4.3  -4.4  -8.7   0.0  2018
328    Trey McKinney-Jones  SG  27  IND   1   0    1   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0   0.0    0.0    NaN  117.0    0.0    NaN   NaN    NaN   0.0    0.0   0.0   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0 -0.001  -5.8  -0.1  -5.9   0.0  2018
331         Josh McRoberts  PF  30  DAL   2   0    6   0.0   8.4  0.000   0.0   8.4  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0  16.7    0.0    0.0  117.0  -12.5  0.000   1.0  0.000   0.0    0.0   0.0   0.0   0.0   0.0    0.0   7.6  0.0  0.0  0.0 -0.190  -9.8  -2.4 -12.2   0.0  2018
343        Naz Mitrou-Long  SG  24  UTA   1   0    1  50.1  50.1  1.000  50.1  50.1  1.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0   0.0  150.4  300.0  113.0  133.8  1.500   1.0  0.000   0.0    0.0   0.0   0.0   0.0   0.0    0.0  45.0  0.1  0.0  0.1  2.712  68.6 -14.2  54.4   0.0  2018
347              Ben Moore  PF  22  IND   2   0    9   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   5.6   5.6   5.6  0.0  0.0   0.0  22.2    0.0  222.0  113.0   -2.3    NaN   NaN    NaN   0.0   12.5   6.3  13.1   0.0   0.0    NaN   0.0  0.0  0.0  0.0  0.072  -5.3   0.3  -5.0   0.0  2018
463         David Stockton  PG  26  UTA   3   0    9  11.1  16.7  0.667  11.1  16.7  0.667  0.0  0.0  NaN  22.3  22.3  1.0   0.0   0.0   0.0   0.0  0.0  0.0   5.6  16.7   55.7  162.0  113.0   33.9  1.050   1.0  1.333   0.0    0.0   0.0   0.0   0.0   0.0   17.4  28.8  0.1  0.0  0.1  0.459  14.8  -8.1   6.7   0.0  2018
464           Julyan Stone  SG  29  CHO  23   0  175   1.7   3.6  0.462   1.7   3.6  0.462  0.0  0.0  NaN   0.3   0.6  0.5   0.3   7.8   8.1   7.2  1.1  0.6   2.0   5.9    5.3  123.0  110.0    7.6  0.684   1.0  0.154   0.6   17.6   9.0  19.2   1.1   1.0   33.5   5.2  0.2  0.2  0.3  0.087  -2.1   0.3  -1.8   0.0  2018
743           Danuel House  SG  23  WAS   1   0    1   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0  49.3  49.3   0.0  0.0  0.0   0.0   0.0    0.0    NaN   89.0   12.2    NaN   NaN    NaN   0.0  100.0  56.4   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0  0.163 -16.4  -4.4 -20.8   0.0  2017
748            R.J. Hunter  SG  23  CHI   3   0    9   0.0   5.6  0.000   0.0   5.6  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   5.6   5.6   0.0  0.0  0.0   0.0   0.0    0.0    0.0  113.0   -3.2  0.000   1.0  0.000   0.0   12.1   6.0   0.0   0.0   0.0    0.0   4.8  0.0  0.0  0.0 -0.088  -9.4  -2.0 -11.4   0.0  2017
1137            Sam Dekker  PF  21  HOU   3   0    6   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   8.2   8.2   0.0  8.2  0.0   0.0   0.0    0.0    NaN   95.0   10.8    NaN   NaN    NaN   0.0   18.5   9.2   0.0   8.2   0.0    NaN   0.0  0.0  0.0  0.0  0.116  -5.3   5.8   0.5   0.0  2016
1208            Joe Harris  SG  24  CLE   5   0   15   3.4  13.7  0.250   3.4  13.7  0.250  0.0  0.0  NaN   0.0   0.0  0.0   0.0  10.3  10.3   6.9  0.0  0.0   3.4   3.4   10.3   81.0  107.0    3.4  0.375   1.0  0.000   0.0   22.5  11.3  18.2   0.0   0.0   20.0  15.1  0.0  0.0  0.0 -0.032  -5.0  -1.6  -6.6   0.0  2016
1401         Nate Robinson  PG  31  NOP   2   1   23   0.0   2.2  0.000   0.0   2.2  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   8.6  2.2  0.0   0.0  10.8    0.0  121.0  113.0    2.6  0.000   1.0  0.000   0.0    0.0   0.0  21.8   2.2   0.0    0.0   1.9  0.0  0.0  0.0  0.038  -6.1  -4.7 -10.8  -0.1  2016
1545      Jerrelle Benimon  PF  23  UTA   2   0    3   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0  17.7  35.4  53.1   0.0  0.0  0.0  17.7   0.0    0.0   46.0   93.0    4.7    NaN   NaN    NaN  38.7   76.6  57.8   0.0   0.0   0.0  100.0  15.3  0.0  0.0  0.0 -0.215 -20.3  -6.6 -26.9   0.0  2015
1621         Andre Dawkins  SG  23  MIA   4   0   22   2.4  14.4  0.167   2.4  14.4  0.167  0.0  0.0  NaN   0.0   0.0  0.0   0.0   4.8   4.8   2.4  0.0  0.0   2.4   7.2    7.2   53.0  113.0   -5.0  0.250   1.0  0.000   0.0   10.7   5.5   6.6   0.0   0.0   14.3  15.0 -0.1  0.0 -0.1 -0.172  -7.5  -3.9 -11.5  -0.1  2015
1658       Jamaal Franklin  SG  23  DEN   3   0   13   3.8   7.7  0.500   3.8   7.7  0.500  0.0  0.0  NaN   0.0   0.0  0.0   3.8   3.8   7.7  11.5  0.0  3.8  11.5  15.4   11.5   83.0  110.0    4.9  0.750   1.0  0.000   8.0    8.6   8.3  32.8   0.0   6.0   60.0  16.6  0.0  0.0  0.0 -0.063  -4.8  -0.3  -5.1   0.0  2015
1948          Ronny Turiaf   C  32  MIN   2   0   19   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   2.7   2.7   5.4  0.0  0.0   0.0   0.0    0.0  214.0  119.0    4.3    NaN   NaN    NaN   0.0    6.2   3.0  14.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0  0.009  -5.6  -2.1  -7.7   0.0  2015
2048          Keith Bogans  SG  33  BOS   6   0   55   2.8   5.6  0.500   2.8   5.6  0.500  0.0  0.0  NaN   2.8   2.8  1.0   0.0   2.8   2.8   2.8  0.9  0.0   0.9   1.9   11.2  153.0  113.0    9.9  0.820   1.0  0.500   0.0    6.4   3.1   7.7   0.9   0.0   12.0   6.7  0.1  0.0  0.1  0.121   0.1  -2.2  -2.1   0.0  2014
2084        Josh Childress  SF  30  NOP   4   0   24   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   6.5   6.5   4.3  2.2  0.0   2.2   2.2    0.0   68.0  111.0    3.9    NaN   NaN    NaN   0.0   14.7   7.3  10.7   2.2   0.0  100.0   1.9  0.0  0.0  0.0 -0.003  -6.2   2.0  -4.3   0.0  2014
2391           Chris Smith  PG  26  NYK   2   0    2   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0   0.0    0.0    NaN  119.0    0.0    NaN   NaN    NaN   0.0    0.0   0.0   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0 -0.020  -5.8  -0.5  -6.2   0.0  2014
2547          Matt Carroll  SG  32  CHA   1   0    6   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   8.7  0.0  0.0   0.0   8.7    0.0  217.0  121.0    2.9    NaN   NaN    NaN   0.0    0.0   0.0  23.4   0.0   0.0    NaN   0.0  0.0  0.0  0.0  0.029  -7.6  -7.8 -15.4   0.0  2013
2685          Damion James  SF  25  BRK   2   0    0   NaN   NaN    NaN   NaN   NaN  0.000  NaN  NaN  NaN   NaN   NaN  0.0   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN   NaN    NaN   NaN   NaN   NaN   NaN    NaN   NaN  0.0  0.0  0.0    NaN  -5.5   0.3  -5.2   0.0  2013
3677            Gani Lawal  PF  22  PHO   1   0    2   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0  25.4    0.0    NaN  117.0   -9.1    NaN   NaN    NaN   0.0    0.0   0.0   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0 -0.009  -5.4   0.5  -4.9   0.0  2011
3790         Bobby Simmons  SF  30  SAS   2   0   16   0.0   9.8  0.000   0.0   9.8  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   6.5  0.0  0.0   0.0   6.5    0.0   40.0  114.0   -5.5  0.000   1.0  0.000   0.0    0.0   0.0  15.7   0.0   0.0    0.0   8.6  0.0  0.0  0.0 -0.138  -8.6  -5.6 -14.3   0.0  2011
3791         Brian Skinner   C  34  MIL   2   0    6   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0   0.0    0.0    NaN  112.0    0.0    NaN   NaN    NaN   0.0    0.0   0.0   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0  0.023  -7.2   1.3  -6.0   0.0  2011
3852      Hassan Whiteside   C  21  SAC   1   0    2   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0  50.4    0.0    NaN  115.0  -17.9    NaN   NaN    NaN   0.0    0.0   0.0   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0  0.007  -6.5   0.0  -6.5   0.0  2011
3971         JamesOn Curry  PG  24  LAC   1   0    0   NaN   NaN    NaN   NaN   NaN  0.000  NaN  NaN  NaN   NaN   NaN  0.0   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN   NaN    NaN   NaN   NaN   NaN   NaN    NaN   NaN  0.0  0.0  0.0    NaN  -6.7  -0.2  -6.9   0.0  2010
4110          Dwayne Jones  PF  26  PHO   2   0    7   0.0   0.0    NaN   0.0   0.0  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0  14.4  14.4   0.0  0.0  0.0   0.0   7.2    0.0    NaN  108.0    1.4    NaN   NaN    NaN   0.0   30.5  16.1   0.0   0.0   0.0    NaN   0.0  0.0  0.0  0.0  0.045  -7.4  -0.8  -8.2   0.0  2010
4731       Martell Webster  SF  22  POR   1   0    5   0.0  11.1  0.000   0.0  11.1  0.000  0.0  0.0  NaN   0.0   0.0  0.0   0.0   0.0   0.0   0.0  0.0  0.0   0.0   0.0    0.0    0.0  117.0   -8.4  0.000   1.0  0.000   0.0    0.0   0.0   0.0   0.0   0.0    0.0   9.4  0.0  0.0  0.0 -0.204  -8.8  -2.9 -11.7   0.0  2009

As we can see above, all these observations had a null value in the `2P%` column because they didn't even attempt a shot! At this point, because all the observations we've seen have been players with little to no playing time in addition to the fact that there are so few of them, I'm going to replace all the remaining null values in the dataframe with `0`.

In [192]:
df_all.fillna(value = 0.0, inplace = True)

In [194]:
df_all.isnull().sum()

Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
ORtg      0
DRtg      0
PER       0
TS%       0
3PAr      0
FTr       0
ORB%      0
DRB%      0
TRB%      0
AST%      0
STL%      0
BLK%      0
TOV%      0
USG%      0
OWS       0
DWS       0
WS        0
WS/48     0
OBPM      0
DBPM      0
BPM       0
VORP      0
Year      0
dtype: int64

### NO MORE NULL VALUES!

In [195]:
print('Are the number of rows of all the DataFrames equal to the combined DataFrame? ', 
      (df_2018.shape[0] + df_2017.shape[0] + df_2016.shape[0] + df_2015.shape[0] + df_2014.shape[0] + 
       df_2013.shape[0] + df_2012.shape[0] + df_2011.shape[0] + df_2010.shape[0] + df_2009.shape[0]) == df_all.shape[0])

Are the number of rows of all the DataFrames equal to the combined DataFrame?  True

It looks like we got a data set that is ready to explore! So we'll export it to a `csv` and then move on to the next step: Exploratory Data Analysis!

In [197]:
# export combined df to csv
df_all.to_csv('data/df_all.csv')

- [Selecting/Excluding Sets of Columns in pandas](https://stackoverflow.com/questions/14940743/selecting-excluding-sets-of-columns-in-pandas)

- [Change data type of columns in pandas](https://stackoverflow.com/questions/15891038/change-data-type-of-columns-in-pandas)

- [to_numeric for multiple columns](https://stackoverflow.com/questions/36814100/pandas-to-numeric-for-multiple-columns)